// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JetProtos.proto

package com.gobestsoft.proto.protobuf;

public interface PersonTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int 类型
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.PersonTest.Sex sex = 4;</code>
   */
  int getSexValue();
  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.PersonTest.Sex sex = 4;</code>
   */
  com.gobestsoft.proto.protobuf.PersonTest.Sex getSex();

  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  java.util.List<com.gobestsoft.proto.protobuf.PersonTest.PhoneNumber> 
      getPhoneList();
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  com.gobestsoft.proto.protobuf.PersonTest.PhoneNumber getPhone(int index);
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  int getPhoneCount();
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  java.util.List<? extends com.gobestsoft.proto.protobuf.PersonTest.PhoneNumberOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  com.gobestsoft.proto.protobuf.PersonTest.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);

  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  int getTagsCount();
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);
}
