// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

/**
 * <pre>
 * aoe伤害
 * </pre>
 *
 * Protobuf type {@code AOEDamageMessage}
 */
public  final class AOEDamageMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AOEDamageMessage)
    AOEDamageMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AOEDamageMessage.newBuilder() to construct.
  private AOEDamageMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AOEDamageMessage() {
    defIds_ = emptyIntList();
    defHps_ = emptyIntList();
    damArray_ = emptyIntList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AOEDamageMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            attId_ = input.readInt32();
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              defIds_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            defIds_.addInt(input.readInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              defIds_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              defIds_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              defHps_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            defHps_.addInt(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
              defHps_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              defHps_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {

            attackTimes_ = input.readInt32();
            break;
          }
          case 40: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              damArray_ = newIntList();
              mutable_bitField0_ |= 0x00000010;
            }
            damArray_.addInt(input.readInt32());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000010) != 0) && input.getBytesUntilLimit() > 0) {
              damArray_ = newIntList();
              mutable_bitField0_ |= 0x00000010;
            }
            while (input.getBytesUntilLimit() > 0) {
              damArray_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 48: {

            hit_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        defIds_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        defHps_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        damArray_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_AOEDamageMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_AOEDamageMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf2.AOEDamageMessage.class, com.mumu.proto.protobuf2.AOEDamageMessage.Builder.class);
  }

  private int bitField0_;
  public static final int ATTID_FIELD_NUMBER = 1;
  private int attId_;
  /**
   * <pre>
   * 攻击方Id
   * </pre>
   *
   * <code>int32 attId = 1;</code>
   */
  public int getAttId() {
    return attId_;
  }

  public static final int DEFIDS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.IntList defIds_;
  /**
   * <pre>
   * 受击方
   * </pre>
   *
   * <code>repeated int32 defIds = 2;</code>
   */
  public java.util.List<java.lang.Integer>
      getDefIdsList() {
    return defIds_;
  }
  /**
   * <pre>
   * 受击方
   * </pre>
   *
   * <code>repeated int32 defIds = 2;</code>
   */
  public int getDefIdsCount() {
    return defIds_.size();
  }
  /**
   * <pre>
   * 受击方
   * </pre>
   *
   * <code>repeated int32 defIds = 2;</code>
   */
  public int getDefIds(int index) {
    return defIds_.getInt(index);
  }
  private int defIdsMemoizedSerializedSize = -1;

  public static final int DEFHPS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList defHps_;
  /**
   * <pre>
   * 受击方血量
   * </pre>
   *
   * <code>repeated int32 defHps = 3;</code>
   */
  public java.util.List<java.lang.Integer>
      getDefHpsList() {
    return defHps_;
  }
  /**
   * <pre>
   * 受击方血量
   * </pre>
   *
   * <code>repeated int32 defHps = 3;</code>
   */
  public int getDefHpsCount() {
    return defHps_.size();
  }
  /**
   * <pre>
   * 受击方血量
   * </pre>
   *
   * <code>repeated int32 defHps = 3;</code>
   */
  public int getDefHps(int index) {
    return defHps_.getInt(index);
  }
  private int defHpsMemoizedSerializedSize = -1;

  public static final int ATTACKTIMES_FIELD_NUMBER = 4;
  private int attackTimes_;
  /**
   * <pre>
   * 攻击次数
   * </pre>
   *
   * <code>int32 attackTimes = 4;</code>
   */
  public int getAttackTimes() {
    return attackTimes_;
  }

  public static final int DAMARRAY_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.IntList damArray_;
  /**
   * <pre>
   * 伤害数组
   * </pre>
   *
   * <code>repeated int32 damArray = 5;</code>
   */
  public java.util.List<java.lang.Integer>
      getDamArrayList() {
    return damArray_;
  }
  /**
   * <pre>
   * 伤害数组
   * </pre>
   *
   * <code>repeated int32 damArray = 5;</code>
   */
  public int getDamArrayCount() {
    return damArray_.size();
  }
  /**
   * <pre>
   * 伤害数组
   * </pre>
   *
   * <code>repeated int32 damArray = 5;</code>
   */
  public int getDamArray(int index) {
    return damArray_.getInt(index);
  }
  private int damArrayMemoizedSerializedSize = -1;

  public static final int HIT_FIELD_NUMBER = 6;
  private boolean hit_;
  /**
   * <pre>
   * 是否命中目标
   * </pre>
   *
   * <code>bool hit = 6;</code>
   */
  public boolean getHit() {
    return hit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (attId_ != 0) {
      output.writeInt32(1, attId_);
    }
    if (getDefIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(defIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < defIds_.size(); i++) {
      output.writeInt32NoTag(defIds_.getInt(i));
    }
    if (getDefHpsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(defHpsMemoizedSerializedSize);
    }
    for (int i = 0; i < defHps_.size(); i++) {
      output.writeInt32NoTag(defHps_.getInt(i));
    }
    if (attackTimes_ != 0) {
      output.writeInt32(4, attackTimes_);
    }
    if (getDamArrayList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(damArrayMemoizedSerializedSize);
    }
    for (int i = 0; i < damArray_.size(); i++) {
      output.writeInt32NoTag(damArray_.getInt(i));
    }
    if (hit_ != false) {
      output.writeBool(6, hit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (attId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, attId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < defIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(defIds_.getInt(i));
      }
      size += dataSize;
      if (!getDefIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      defIdsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < defHps_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(defHps_.getInt(i));
      }
      size += dataSize;
      if (!getDefHpsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      defHpsMemoizedSerializedSize = dataSize;
    }
    if (attackTimes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, attackTimes_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < damArray_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(damArray_.getInt(i));
      }
      size += dataSize;
      if (!getDamArrayList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      damArrayMemoizedSerializedSize = dataSize;
    }
    if (hit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, hit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf2.AOEDamageMessage)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf2.AOEDamageMessage other = (com.mumu.proto.protobuf2.AOEDamageMessage) obj;

    if (getAttId()
        != other.getAttId()) return false;
    if (!getDefIdsList()
        .equals(other.getDefIdsList())) return false;
    if (!getDefHpsList()
        .equals(other.getDefHpsList())) return false;
    if (getAttackTimes()
        != other.getAttackTimes()) return false;
    if (!getDamArrayList()
        .equals(other.getDamArrayList())) return false;
    if (getHit()
        != other.getHit()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ATTID_FIELD_NUMBER;
    hash = (53 * hash) + getAttId();
    if (getDefIdsCount() > 0) {
      hash = (37 * hash) + DEFIDS_FIELD_NUMBER;
      hash = (53 * hash) + getDefIdsList().hashCode();
    }
    if (getDefHpsCount() > 0) {
      hash = (37 * hash) + DEFHPS_FIELD_NUMBER;
      hash = (53 * hash) + getDefHpsList().hashCode();
    }
    hash = (37 * hash) + ATTACKTIMES_FIELD_NUMBER;
    hash = (53 * hash) + getAttackTimes();
    if (getDamArrayCount() > 0) {
      hash = (37 * hash) + DAMARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getDamArrayList().hashCode();
    }
    hash = (37 * hash) + HIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHit());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.AOEDamageMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf2.AOEDamageMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * aoe伤害
   * </pre>
   *
   * Protobuf type {@code AOEDamageMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AOEDamageMessage)
      com.mumu.proto.protobuf2.AOEDamageMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_AOEDamageMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_AOEDamageMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf2.AOEDamageMessage.class, com.mumu.proto.protobuf2.AOEDamageMessage.Builder.class);
    }

    // Construct using com.mumu.proto.protobuf2.AOEDamageMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      attId_ = 0;

      defIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      defHps_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      attackTimes_ = 0;

      damArray_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000010);
      hit_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_AOEDamageMessage_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.AOEDamageMessage getDefaultInstanceForType() {
      return com.mumu.proto.protobuf2.AOEDamageMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.AOEDamageMessage build() {
      com.mumu.proto.protobuf2.AOEDamageMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.AOEDamageMessage buildPartial() {
      com.mumu.proto.protobuf2.AOEDamageMessage result = new com.mumu.proto.protobuf2.AOEDamageMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.attId_ = attId_;
      if (((bitField0_ & 0x00000002) != 0)) {
        defIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.defIds_ = defIds_;
      if (((bitField0_ & 0x00000004) != 0)) {
        defHps_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.defHps_ = defHps_;
      result.attackTimes_ = attackTimes_;
      if (((bitField0_ & 0x00000010) != 0)) {
        damArray_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.damArray_ = damArray_;
      result.hit_ = hit_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf2.AOEDamageMessage) {
        return mergeFrom((com.mumu.proto.protobuf2.AOEDamageMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf2.AOEDamageMessage other) {
      if (other == com.mumu.proto.protobuf2.AOEDamageMessage.getDefaultInstance()) return this;
      if (other.getAttId() != 0) {
        setAttId(other.getAttId());
      }
      if (!other.defIds_.isEmpty()) {
        if (defIds_.isEmpty()) {
          defIds_ = other.defIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDefIdsIsMutable();
          defIds_.addAll(other.defIds_);
        }
        onChanged();
      }
      if (!other.defHps_.isEmpty()) {
        if (defHps_.isEmpty()) {
          defHps_ = other.defHps_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDefHpsIsMutable();
          defHps_.addAll(other.defHps_);
        }
        onChanged();
      }
      if (other.getAttackTimes() != 0) {
        setAttackTimes(other.getAttackTimes());
      }
      if (!other.damArray_.isEmpty()) {
        if (damArray_.isEmpty()) {
          damArray_ = other.damArray_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureDamArrayIsMutable();
          damArray_.addAll(other.damArray_);
        }
        onChanged();
      }
      if (other.getHit() != false) {
        setHit(other.getHit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf2.AOEDamageMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf2.AOEDamageMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int attId_ ;
    /**
     * <pre>
     * 攻击方Id
     * </pre>
     *
     * <code>int32 attId = 1;</code>
     */
    public int getAttId() {
      return attId_;
    }
    /**
     * <pre>
     * 攻击方Id
     * </pre>
     *
     * <code>int32 attId = 1;</code>
     */
    public Builder setAttId(int value) {
      
      attId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 攻击方Id
     * </pre>
     *
     * <code>int32 attId = 1;</code>
     */
    public Builder clearAttId() {
      
      attId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList defIds_ = emptyIntList();
    private void ensureDefIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        defIds_ = mutableCopy(defIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * 受击方
     * </pre>
     *
     * <code>repeated int32 defIds = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getDefIdsList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(defIds_) : defIds_;
    }
    /**
     * <pre>
     * 受击方
     * </pre>
     *
     * <code>repeated int32 defIds = 2;</code>
     */
    public int getDefIdsCount() {
      return defIds_.size();
    }
    /**
     * <pre>
     * 受击方
     * </pre>
     *
     * <code>repeated int32 defIds = 2;</code>
     */
    public int getDefIds(int index) {
      return defIds_.getInt(index);
    }
    /**
     * <pre>
     * 受击方
     * </pre>
     *
     * <code>repeated int32 defIds = 2;</code>
     */
    public Builder setDefIds(
        int index, int value) {
      ensureDefIdsIsMutable();
      defIds_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方
     * </pre>
     *
     * <code>repeated int32 defIds = 2;</code>
     */
    public Builder addDefIds(int value) {
      ensureDefIdsIsMutable();
      defIds_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方
     * </pre>
     *
     * <code>repeated int32 defIds = 2;</code>
     */
    public Builder addAllDefIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDefIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, defIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方
     * </pre>
     *
     * <code>repeated int32 defIds = 2;</code>
     */
    public Builder clearDefIds() {
      defIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList defHps_ = emptyIntList();
    private void ensureDefHpsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        defHps_ = mutableCopy(defHps_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>repeated int32 defHps = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getDefHpsList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(defHps_) : defHps_;
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>repeated int32 defHps = 3;</code>
     */
    public int getDefHpsCount() {
      return defHps_.size();
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>repeated int32 defHps = 3;</code>
     */
    public int getDefHps(int index) {
      return defHps_.getInt(index);
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>repeated int32 defHps = 3;</code>
     */
    public Builder setDefHps(
        int index, int value) {
      ensureDefHpsIsMutable();
      defHps_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>repeated int32 defHps = 3;</code>
     */
    public Builder addDefHps(int value) {
      ensureDefHpsIsMutable();
      defHps_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>repeated int32 defHps = 3;</code>
     */
    public Builder addAllDefHps(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDefHpsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, defHps_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>repeated int32 defHps = 3;</code>
     */
    public Builder clearDefHps() {
      defHps_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private int attackTimes_ ;
    /**
     * <pre>
     * 攻击次数
     * </pre>
     *
     * <code>int32 attackTimes = 4;</code>
     */
    public int getAttackTimes() {
      return attackTimes_;
    }
    /**
     * <pre>
     * 攻击次数
     * </pre>
     *
     * <code>int32 attackTimes = 4;</code>
     */
    public Builder setAttackTimes(int value) {
      
      attackTimes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 攻击次数
     * </pre>
     *
     * <code>int32 attackTimes = 4;</code>
     */
    public Builder clearAttackTimes() {
      
      attackTimes_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList damArray_ = emptyIntList();
    private void ensureDamArrayIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        damArray_ = mutableCopy(damArray_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <pre>
     * 伤害数组
     * </pre>
     *
     * <code>repeated int32 damArray = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getDamArrayList() {
      return ((bitField0_ & 0x00000010) != 0) ?
               java.util.Collections.unmodifiableList(damArray_) : damArray_;
    }
    /**
     * <pre>
     * 伤害数组
     * </pre>
     *
     * <code>repeated int32 damArray = 5;</code>
     */
    public int getDamArrayCount() {
      return damArray_.size();
    }
    /**
     * <pre>
     * 伤害数组
     * </pre>
     *
     * <code>repeated int32 damArray = 5;</code>
     */
    public int getDamArray(int index) {
      return damArray_.getInt(index);
    }
    /**
     * <pre>
     * 伤害数组
     * </pre>
     *
     * <code>repeated int32 damArray = 5;</code>
     */
    public Builder setDamArray(
        int index, int value) {
      ensureDamArrayIsMutable();
      damArray_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 伤害数组
     * </pre>
     *
     * <code>repeated int32 damArray = 5;</code>
     */
    public Builder addDamArray(int value) {
      ensureDamArrayIsMutable();
      damArray_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 伤害数组
     * </pre>
     *
     * <code>repeated int32 damArray = 5;</code>
     */
    public Builder addAllDamArray(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDamArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, damArray_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 伤害数组
     * </pre>
     *
     * <code>repeated int32 damArray = 5;</code>
     */
    public Builder clearDamArray() {
      damArray_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private boolean hit_ ;
    /**
     * <pre>
     * 是否命中目标
     * </pre>
     *
     * <code>bool hit = 6;</code>
     */
    public boolean getHit() {
      return hit_;
    }
    /**
     * <pre>
     * 是否命中目标
     * </pre>
     *
     * <code>bool hit = 6;</code>
     */
    public Builder setHit(boolean value) {
      
      hit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否命中目标
     * </pre>
     *
     * <code>bool hit = 6;</code>
     */
    public Builder clearHit() {
      
      hit_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AOEDamageMessage)
  }

  // @@protoc_insertion_point(class_scope:AOEDamageMessage)
  private static final com.mumu.proto.protobuf2.AOEDamageMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf2.AOEDamageMessage();
  }

  public static com.mumu.proto.protobuf2.AOEDamageMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AOEDamageMessage>
      PARSER = new com.google.protobuf.AbstractParser<AOEDamageMessage>() {
    @java.lang.Override
    public AOEDamageMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AOEDamageMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AOEDamageMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AOEDamageMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf2.AOEDamageMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

