// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface AOEDamageMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AOEDamageMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 攻击方Id
   * </pre>
   *
   * <code>int32 attId = 1;</code>
   */
  int getAttId();

  /**
   * <pre>
   * 受击方
   * </pre>
   *
   * <code>repeated int32 defIds = 2;</code>
   */
  java.util.List<java.lang.Integer> getDefIdsList();
  /**
   * <pre>
   * 受击方
   * </pre>
   *
   * <code>repeated int32 defIds = 2;</code>
   */
  int getDefIdsCount();
  /**
   * <pre>
   * 受击方
   * </pre>
   *
   * <code>repeated int32 defIds = 2;</code>
   */
  int getDefIds(int index);

  /**
   * <pre>
   * 受击方血量
   * </pre>
   *
   * <code>repeated int32 defHps = 3;</code>
   */
  java.util.List<java.lang.Integer> getDefHpsList();
  /**
   * <pre>
   * 受击方血量
   * </pre>
   *
   * <code>repeated int32 defHps = 3;</code>
   */
  int getDefHpsCount();
  /**
   * <pre>
   * 受击方血量
   * </pre>
   *
   * <code>repeated int32 defHps = 3;</code>
   */
  int getDefHps(int index);

  /**
   * <pre>
   * 攻击次数
   * </pre>
   *
   * <code>int32 attackTimes = 4;</code>
   */
  int getAttackTimes();

  /**
   * <pre>
   * 伤害数组
   * </pre>
   *
   * <code>repeated int32 damArray = 5;</code>
   */
  java.util.List<java.lang.Integer> getDamArrayList();
  /**
   * <pre>
   * 伤害数组
   * </pre>
   *
   * <code>repeated int32 damArray = 5;</code>
   */
  int getDamArrayCount();
  /**
   * <pre>
   * 伤害数组
   * </pre>
   *
   * <code>repeated int32 damArray = 5;</code>
   */
  int getDamArray(int index);

  /**
   * <pre>
   * 是否命中目标
   * </pre>
   *
   * <code>bool hit = 6;</code>
   */
  boolean getHit();
}
