// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface AttackMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AttackMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 单体伤害
   * </pre>
   *
   * <code>.MonomerDamageMessage monomer = 1;</code>
   */
  boolean hasMonomer();
  /**
   * <pre>
   * 单体伤害
   * </pre>
   *
   * <code>.MonomerDamageMessage monomer = 1;</code>
   */
  com.mumu.proto.protobuf2.MonomerDamageMessage getMonomer();
  /**
   * <pre>
   * 单体伤害
   * </pre>
   *
   * <code>.MonomerDamageMessage monomer = 1;</code>
   */
  com.mumu.proto.protobuf2.MonomerDamageMessageOrBuilder getMonomerOrBuilder();

  /**
   * <pre>
   * aoe伤害
   * </pre>
   *
   * <code>.AOEDamageMessage aoe = 2;</code>
   */
  boolean hasAoe();
  /**
   * <pre>
   * aoe伤害
   * </pre>
   *
   * <code>.AOEDamageMessage aoe = 2;</code>
   */
  com.mumu.proto.protobuf2.AOEDamageMessage getAoe();
  /**
   * <pre>
   * aoe伤害
   * </pre>
   *
   * <code>.AOEDamageMessage aoe = 2;</code>
   */
  com.mumu.proto.protobuf2.AOEDamageMessageOrBuilder getAoeOrBuilder();

  /**
   * <pre>
   * 护盾吸收伤害
   * </pre>
   *
   * <code>int32 shieldOffset = 3;</code>
   */
  int getShieldOffset();

  /**
   * <pre>
   * 防守方teamId
   * </pre>
   *
   * <code>int32 defTeamId = 4;</code>
   */
  int getDefTeamId();
}
