// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface BattleEndMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BattleEndMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 战斗Id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();
}
