// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface BattleFieldMixMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BattleFieldMixMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 幸存的战场id
   * </pre>
   *
   * <code>int32 surviveId = 1;</code>
   */
  int getSurviveId();

  /**
   * <pre>
   * 被融合的战场id
   * </pre>
   *
   * <code>int32 mixedId = 2;</code>
   */
  int getMixedId();
}
