// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

/**
 * <pre>
 * 战场融合 ProtoId 6
 * </pre>
 *
 * Protobuf type {@code BattleFieldMixMessage}
 */
public  final class BattleFieldMixMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BattleFieldMixMessage)
    BattleFieldMixMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BattleFieldMixMessage.newBuilder() to construct.
  private BattleFieldMixMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BattleFieldMixMessage() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BattleFieldMixMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            surviveId_ = input.readInt32();
            break;
          }
          case 16: {

            mixedId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_BattleFieldMixMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_BattleFieldMixMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf2.BattleFieldMixMessage.class, com.mumu.proto.protobuf2.BattleFieldMixMessage.Builder.class);
  }

  public static final int SURVIVEID_FIELD_NUMBER = 1;
  private int surviveId_;
  /**
   * <pre>
   * 幸存的战场id
   * </pre>
   *
   * <code>int32 surviveId = 1;</code>
   */
  public int getSurviveId() {
    return surviveId_;
  }

  public static final int MIXEDID_FIELD_NUMBER = 2;
  private int mixedId_;
  /**
   * <pre>
   * 被融合的战场id
   * </pre>
   *
   * <code>int32 mixedId = 2;</code>
   */
  public int getMixedId() {
    return mixedId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (surviveId_ != 0) {
      output.writeInt32(1, surviveId_);
    }
    if (mixedId_ != 0) {
      output.writeInt32(2, mixedId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (surviveId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, surviveId_);
    }
    if (mixedId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, mixedId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf2.BattleFieldMixMessage)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf2.BattleFieldMixMessage other = (com.mumu.proto.protobuf2.BattleFieldMixMessage) obj;

    if (getSurviveId()
        != other.getSurviveId()) return false;
    if (getMixedId()
        != other.getMixedId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SURVIVEID_FIELD_NUMBER;
    hash = (53 * hash) + getSurviveId();
    hash = (37 * hash) + MIXEDID_FIELD_NUMBER;
    hash = (53 * hash) + getMixedId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.BattleFieldMixMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf2.BattleFieldMixMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 战场融合 ProtoId 6
   * </pre>
   *
   * Protobuf type {@code BattleFieldMixMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BattleFieldMixMessage)
      com.mumu.proto.protobuf2.BattleFieldMixMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_BattleFieldMixMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_BattleFieldMixMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf2.BattleFieldMixMessage.class, com.mumu.proto.protobuf2.BattleFieldMixMessage.Builder.class);
    }

    // Construct using com.mumu.proto.protobuf2.BattleFieldMixMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      surviveId_ = 0;

      mixedId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_BattleFieldMixMessage_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.BattleFieldMixMessage getDefaultInstanceForType() {
      return com.mumu.proto.protobuf2.BattleFieldMixMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.BattleFieldMixMessage build() {
      com.mumu.proto.protobuf2.BattleFieldMixMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.BattleFieldMixMessage buildPartial() {
      com.mumu.proto.protobuf2.BattleFieldMixMessage result = new com.mumu.proto.protobuf2.BattleFieldMixMessage(this);
      result.surviveId_ = surviveId_;
      result.mixedId_ = mixedId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf2.BattleFieldMixMessage) {
        return mergeFrom((com.mumu.proto.protobuf2.BattleFieldMixMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf2.BattleFieldMixMessage other) {
      if (other == com.mumu.proto.protobuf2.BattleFieldMixMessage.getDefaultInstance()) return this;
      if (other.getSurviveId() != 0) {
        setSurviveId(other.getSurviveId());
      }
      if (other.getMixedId() != 0) {
        setMixedId(other.getMixedId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf2.BattleFieldMixMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf2.BattleFieldMixMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int surviveId_ ;
    /**
     * <pre>
     * 幸存的战场id
     * </pre>
     *
     * <code>int32 surviveId = 1;</code>
     */
    public int getSurviveId() {
      return surviveId_;
    }
    /**
     * <pre>
     * 幸存的战场id
     * </pre>
     *
     * <code>int32 surviveId = 1;</code>
     */
    public Builder setSurviveId(int value) {
      
      surviveId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 幸存的战场id
     * </pre>
     *
     * <code>int32 surviveId = 1;</code>
     */
    public Builder clearSurviveId() {
      
      surviveId_ = 0;
      onChanged();
      return this;
    }

    private int mixedId_ ;
    /**
     * <pre>
     * 被融合的战场id
     * </pre>
     *
     * <code>int32 mixedId = 2;</code>
     */
    public int getMixedId() {
      return mixedId_;
    }
    /**
     * <pre>
     * 被融合的战场id
     * </pre>
     *
     * <code>int32 mixedId = 2;</code>
     */
    public Builder setMixedId(int value) {
      
      mixedId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被融合的战场id
     * </pre>
     *
     * <code>int32 mixedId = 2;</code>
     */
    public Builder clearMixedId() {
      
      mixedId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BattleFieldMixMessage)
  }

  // @@protoc_insertion_point(class_scope:BattleFieldMixMessage)
  private static final com.mumu.proto.protobuf2.BattleFieldMixMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf2.BattleFieldMixMessage();
  }

  public static com.mumu.proto.protobuf2.BattleFieldMixMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BattleFieldMixMessage>
      PARSER = new com.google.protobuf.AbstractParser<BattleFieldMixMessage>() {
    @java.lang.Override
    public BattleFieldMixMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BattleFieldMixMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BattleFieldMixMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BattleFieldMixMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf2.BattleFieldMixMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

