// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

/**
 * <pre>
 * 部队切换攻击目标 ProtoId 5
 * </pre>
 *
 * Protobuf type {@code ChangeAttackTeamMessage}
 */
public  final class ChangeAttackTeamMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChangeAttackTeamMessage)
    ChangeAttackTeamMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChangeAttackTeamMessage.newBuilder() to construct.
  private ChangeAttackTeamMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChangeAttackTeamMessage() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChangeAttackTeamMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            attTeamId_ = input.readInt32();
            break;
          }
          case 16: {

            defTeamId_ = input.readInt32();
            break;
          }
          case 24: {

            reloadCd_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_ChangeAttackTeamMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_ChangeAttackTeamMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf2.ChangeAttackTeamMessage.class, com.mumu.proto.protobuf2.ChangeAttackTeamMessage.Builder.class);
  }

  public static final int ATTTEAMID_FIELD_NUMBER = 1;
  private int attTeamId_;
  /**
   * <pre>
   * 攻击编队id
   * </pre>
   *
   * <code>int32 attTeamId = 1;</code>
   */
  public int getAttTeamId() {
    return attTeamId_;
  }

  public static final int DEFTEAMID_FIELD_NUMBER = 2;
  private int defTeamId_;
  /**
   * <pre>
   * 防守编队id
   * </pre>
   *
   * <code>int32 defTeamId = 2;</code>
   */
  public int getDefTeamId() {
    return defTeamId_;
  }

  public static final int RELOADCD_FIELD_NUMBER = 3;
  private int reloadCd_;
  /**
   * <pre>
   * 攻击
   * </pre>
   *
   * <code>int32 reloadCd = 3;</code>
   */
  public int getReloadCd() {
    return reloadCd_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (attTeamId_ != 0) {
      output.writeInt32(1, attTeamId_);
    }
    if (defTeamId_ != 0) {
      output.writeInt32(2, defTeamId_);
    }
    if (reloadCd_ != 0) {
      output.writeInt32(3, reloadCd_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (attTeamId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, attTeamId_);
    }
    if (defTeamId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, defTeamId_);
    }
    if (reloadCd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, reloadCd_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf2.ChangeAttackTeamMessage)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf2.ChangeAttackTeamMessage other = (com.mumu.proto.protobuf2.ChangeAttackTeamMessage) obj;

    if (getAttTeamId()
        != other.getAttTeamId()) return false;
    if (getDefTeamId()
        != other.getDefTeamId()) return false;
    if (getReloadCd()
        != other.getReloadCd()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ATTTEAMID_FIELD_NUMBER;
    hash = (53 * hash) + getAttTeamId();
    hash = (37 * hash) + DEFTEAMID_FIELD_NUMBER;
    hash = (53 * hash) + getDefTeamId();
    hash = (37 * hash) + RELOADCD_FIELD_NUMBER;
    hash = (53 * hash) + getReloadCd();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf2.ChangeAttackTeamMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 部队切换攻击目标 ProtoId 5
   * </pre>
   *
   * Protobuf type {@code ChangeAttackTeamMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChangeAttackTeamMessage)
      com.mumu.proto.protobuf2.ChangeAttackTeamMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_ChangeAttackTeamMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_ChangeAttackTeamMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf2.ChangeAttackTeamMessage.class, com.mumu.proto.protobuf2.ChangeAttackTeamMessage.Builder.class);
    }

    // Construct using com.mumu.proto.protobuf2.ChangeAttackTeamMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      attTeamId_ = 0;

      defTeamId_ = 0;

      reloadCd_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_ChangeAttackTeamMessage_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.ChangeAttackTeamMessage getDefaultInstanceForType() {
      return com.mumu.proto.protobuf2.ChangeAttackTeamMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.ChangeAttackTeamMessage build() {
      com.mumu.proto.protobuf2.ChangeAttackTeamMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.ChangeAttackTeamMessage buildPartial() {
      com.mumu.proto.protobuf2.ChangeAttackTeamMessage result = new com.mumu.proto.protobuf2.ChangeAttackTeamMessage(this);
      result.attTeamId_ = attTeamId_;
      result.defTeamId_ = defTeamId_;
      result.reloadCd_ = reloadCd_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf2.ChangeAttackTeamMessage) {
        return mergeFrom((com.mumu.proto.protobuf2.ChangeAttackTeamMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf2.ChangeAttackTeamMessage other) {
      if (other == com.mumu.proto.protobuf2.ChangeAttackTeamMessage.getDefaultInstance()) return this;
      if (other.getAttTeamId() != 0) {
        setAttTeamId(other.getAttTeamId());
      }
      if (other.getDefTeamId() != 0) {
        setDefTeamId(other.getDefTeamId());
      }
      if (other.getReloadCd() != 0) {
        setReloadCd(other.getReloadCd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf2.ChangeAttackTeamMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf2.ChangeAttackTeamMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int attTeamId_ ;
    /**
     * <pre>
     * 攻击编队id
     * </pre>
     *
     * <code>int32 attTeamId = 1;</code>
     */
    public int getAttTeamId() {
      return attTeamId_;
    }
    /**
     * <pre>
     * 攻击编队id
     * </pre>
     *
     * <code>int32 attTeamId = 1;</code>
     */
    public Builder setAttTeamId(int value) {
      
      attTeamId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 攻击编队id
     * </pre>
     *
     * <code>int32 attTeamId = 1;</code>
     */
    public Builder clearAttTeamId() {
      
      attTeamId_ = 0;
      onChanged();
      return this;
    }

    private int defTeamId_ ;
    /**
     * <pre>
     * 防守编队id
     * </pre>
     *
     * <code>int32 defTeamId = 2;</code>
     */
    public int getDefTeamId() {
      return defTeamId_;
    }
    /**
     * <pre>
     * 防守编队id
     * </pre>
     *
     * <code>int32 defTeamId = 2;</code>
     */
    public Builder setDefTeamId(int value) {
      
      defTeamId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 防守编队id
     * </pre>
     *
     * <code>int32 defTeamId = 2;</code>
     */
    public Builder clearDefTeamId() {
      
      defTeamId_ = 0;
      onChanged();
      return this;
    }

    private int reloadCd_ ;
    /**
     * <pre>
     * 攻击
     * </pre>
     *
     * <code>int32 reloadCd = 3;</code>
     */
    public int getReloadCd() {
      return reloadCd_;
    }
    /**
     * <pre>
     * 攻击
     * </pre>
     *
     * <code>int32 reloadCd = 3;</code>
     */
    public Builder setReloadCd(int value) {
      
      reloadCd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 攻击
     * </pre>
     *
     * <code>int32 reloadCd = 3;</code>
     */
    public Builder clearReloadCd() {
      
      reloadCd_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChangeAttackTeamMessage)
  }

  // @@protoc_insertion_point(class_scope:ChangeAttackTeamMessage)
  private static final com.mumu.proto.protobuf2.ChangeAttackTeamMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf2.ChangeAttackTeamMessage();
  }

  public static com.mumu.proto.protobuf2.ChangeAttackTeamMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChangeAttackTeamMessage>
      PARSER = new com.google.protobuf.AbstractParser<ChangeAttackTeamMessage>() {
    @java.lang.Override
    public ChangeAttackTeamMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChangeAttackTeamMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChangeAttackTeamMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeAttackTeamMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf2.ChangeAttackTeamMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

