// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface DisplayMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DisplayMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 部队id
   * </pre>
   *
   * <code>int32 teamId = 1;</code>
   */
  int getTeamId();

  /**
   * <pre>
   * 数值
   * </pre>
   *
   * <code>int32 num = 2;</code>
   */
  int getNum();

  /**
   * <pre>
   * 类型
   * </pre>
   *
   * <code>int32 type = 3;</code>
   */
  int getType();
}
