// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface FightReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FightReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 每帧协议
   * </pre>
   *
   * <code>repeated bytes payload = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getPayloadList();
  /**
   * <pre>
   * 每帧协议
   * </pre>
   *
   * <code>repeated bytes payload = 1;</code>
   */
  int getPayloadCount();
  /**
   * <pre>
   * 每帧协议
   * </pre>
   *
   * <code>repeated bytes payload = 1;</code>
   */
  com.google.protobuf.ByteString getPayload(int index);
}
