// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

/**
 * <pre>
 * 战斗帧消息
 * </pre>
 *
 * Protobuf type {@code FightFrame}
 */
public  final class FightFrame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FightFrame)
    FightFrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FightFrame.newBuilder() to construct.
  private FightFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FightFrame() {
    messages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FightFrame(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            frameNum_ = input.readInt32();
            break;
          }
          case 24: {

            time_ = input.readInt32();
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              messages_ = new java.util.ArrayList<com.mumu.proto.protobuf2.FightMessage>();
              mutable_bitField0_ |= 0x00000008;
            }
            messages_.add(
                input.readMessage(com.mumu.proto.protobuf2.FightMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        messages_ = java.util.Collections.unmodifiableList(messages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_FightFrame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_FightFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf2.FightFrame.class, com.mumu.proto.protobuf2.FightFrame.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <pre>
   * 战场Id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int FRAMENUM_FIELD_NUMBER = 2;
  private int frameNum_;
  /**
   * <pre>
   * 帧号
   * </pre>
   *
   * <code>int32 frameNum = 2;</code>
   */
  public int getFrameNum() {
    return frameNum_;
  }

  public static final int TIME_FIELD_NUMBER = 3;
  private int time_;
  /**
   * <pre>
   * 当前时间
   * </pre>
   *
   * <code>int32 time = 3;</code>
   */
  public int getTime() {
    return time_;
  }

  public static final int MESSAGES_FIELD_NUMBER = 10;
  private java.util.List<com.mumu.proto.protobuf2.FightMessage> messages_;
  /**
   * <pre>
   * 这帧中包含的协议
   * </pre>
   *
   * <code>repeated .FightMessage messages = 10;</code>
   */
  public java.util.List<com.mumu.proto.protobuf2.FightMessage> getMessagesList() {
    return messages_;
  }
  /**
   * <pre>
   * 这帧中包含的协议
   * </pre>
   *
   * <code>repeated .FightMessage messages = 10;</code>
   */
  public java.util.List<? extends com.mumu.proto.protobuf2.FightMessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <pre>
   * 这帧中包含的协议
   * </pre>
   *
   * <code>repeated .FightMessage messages = 10;</code>
   */
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <pre>
   * 这帧中包含的协议
   * </pre>
   *
   * <code>repeated .FightMessage messages = 10;</code>
   */
  public com.mumu.proto.protobuf2.FightMessage getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <pre>
   * 这帧中包含的协议
   * </pre>
   *
   * <code>repeated .FightMessage messages = 10;</code>
   */
  public com.mumu.proto.protobuf2.FightMessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (frameNum_ != 0) {
      output.writeInt32(2, frameNum_);
    }
    if (time_ != 0) {
      output.writeInt32(3, time_);
    }
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(10, messages_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (frameNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, frameNum_);
    }
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, time_);
    }
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, messages_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf2.FightFrame)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf2.FightFrame other = (com.mumu.proto.protobuf2.FightFrame) obj;

    if (getId()
        != other.getId()) return false;
    if (getFrameNum()
        != other.getFrameNum()) return false;
    if (getTime()
        != other.getTime()) return false;
    if (!getMessagesList()
        .equals(other.getMessagesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + FRAMENUM_FIELD_NUMBER;
    hash = (53 * hash) + getFrameNum();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    if (getMessagesCount() > 0) {
      hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.FightFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf2.FightFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 战斗帧消息
   * </pre>
   *
   * Protobuf type {@code FightFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FightFrame)
      com.mumu.proto.protobuf2.FightFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_FightFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_FightFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf2.FightFrame.class, com.mumu.proto.protobuf2.FightFrame.Builder.class);
    }

    // Construct using com.mumu.proto.protobuf2.FightFrame.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      frameNum_ = 0;

      time_ = 0;

      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_FightFrame_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.FightFrame getDefaultInstanceForType() {
      return com.mumu.proto.protobuf2.FightFrame.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.FightFrame build() {
      com.mumu.proto.protobuf2.FightFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.FightFrame buildPartial() {
      com.mumu.proto.protobuf2.FightFrame result = new com.mumu.proto.protobuf2.FightFrame(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.frameNum_ = frameNum_;
      result.time_ = time_;
      if (messagesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf2.FightFrame) {
        return mergeFrom((com.mumu.proto.protobuf2.FightFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf2.FightFrame other) {
      if (other == com.mumu.proto.protobuf2.FightFrame.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getFrameNum() != 0) {
        setFrameNum(other.getFrameNum());
      }
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      if (messagesBuilder_ == null) {
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
      } else {
        if (!other.messages_.isEmpty()) {
          if (messagesBuilder_.isEmpty()) {
            messagesBuilder_.dispose();
            messagesBuilder_ = null;
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000008);
            messagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessagesFieldBuilder() : null;
          } else {
            messagesBuilder_.addAllMessages(other.messages_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf2.FightFrame parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf2.FightFrame) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <pre>
     * 战场Id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * 战场Id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 战场Id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int frameNum_ ;
    /**
     * <pre>
     * 帧号
     * </pre>
     *
     * <code>int32 frameNum = 2;</code>
     */
    public int getFrameNum() {
      return frameNum_;
    }
    /**
     * <pre>
     * 帧号
     * </pre>
     *
     * <code>int32 frameNum = 2;</code>
     */
    public Builder setFrameNum(int value) {
      
      frameNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 帧号
     * </pre>
     *
     * <code>int32 frameNum = 2;</code>
     */
    public Builder clearFrameNum() {
      
      frameNum_ = 0;
      onChanged();
      return this;
    }

    private int time_ ;
    /**
     * <pre>
     * 当前时间
     * </pre>
     *
     * <code>int32 time = 3;</code>
     */
    public int getTime() {
      return time_;
    }
    /**
     * <pre>
     * 当前时间
     * </pre>
     *
     * <code>int32 time = 3;</code>
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前时间
     * </pre>
     *
     * <code>int32 time = 3;</code>
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.mumu.proto.protobuf2.FightMessage> messages_ =
      java.util.Collections.emptyList();
    private void ensureMessagesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        messages_ = new java.util.ArrayList<com.mumu.proto.protobuf2.FightMessage>(messages_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mumu.proto.protobuf2.FightMessage, com.mumu.proto.protobuf2.FightMessage.Builder, com.mumu.proto.protobuf2.FightMessageOrBuilder> messagesBuilder_;

    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public java.util.List<com.mumu.proto.protobuf2.FightMessage> getMessagesList() {
      if (messagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messages_);
      } else {
        return messagesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public int getMessagesCount() {
      if (messagesBuilder_ == null) {
        return messages_.size();
      } else {
        return messagesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public com.mumu.proto.protobuf2.FightMessage getMessages(int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);
      } else {
        return messagesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder setMessages(
        int index, com.mumu.proto.protobuf2.FightMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder setMessages(
        int index, com.mumu.proto.protobuf2.FightMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.set(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder addMessages(com.mumu.proto.protobuf2.FightMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder addMessages(
        int index, com.mumu.proto.protobuf2.FightMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(index, value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder addMessages(
        com.mumu.proto.protobuf2.FightMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder addMessages(
        int index, com.mumu.proto.protobuf2.FightMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends com.mumu.proto.protobuf2.FightMessage> values) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
      } else {
        messagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public Builder removeMessages(int index) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.remove(index);
        onChanged();
      } else {
        messagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public com.mumu.proto.protobuf2.FightMessage.Builder getMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public com.mumu.proto.protobuf2.FightMessageOrBuilder getMessagesOrBuilder(
        int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);  } else {
        return messagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public java.util.List<? extends com.mumu.proto.protobuf2.FightMessageOrBuilder> 
         getMessagesOrBuilderList() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messages_);
      }
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public com.mumu.proto.protobuf2.FightMessage.Builder addMessagesBuilder() {
      return getMessagesFieldBuilder().addBuilder(
          com.mumu.proto.protobuf2.FightMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public com.mumu.proto.protobuf2.FightMessage.Builder addMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().addBuilder(
          index, com.mumu.proto.protobuf2.FightMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * 这帧中包含的协议
     * </pre>
     *
     * <code>repeated .FightMessage messages = 10;</code>
     */
    public java.util.List<com.mumu.proto.protobuf2.FightMessage.Builder> 
         getMessagesBuilderList() {
      return getMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mumu.proto.protobuf2.FightMessage, com.mumu.proto.protobuf2.FightMessage.Builder, com.mumu.proto.protobuf2.FightMessageOrBuilder> 
        getMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mumu.proto.protobuf2.FightMessage, com.mumu.proto.protobuf2.FightMessage.Builder, com.mumu.proto.protobuf2.FightMessageOrBuilder>(
                messages_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FightFrame)
  }

  // @@protoc_insertion_point(class_scope:FightFrame)
  private static final com.mumu.proto.protobuf2.FightFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf2.FightFrame();
  }

  public static com.mumu.proto.protobuf2.FightFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FightFrame>
      PARSER = new com.google.protobuf.AbstractParser<FightFrame>() {
    @java.lang.Override
    public FightFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FightFrame(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FightFrame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FightFrame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf2.FightFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

