// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

/**
 * <pre>
 * 生成java文件命令 protoc -I=./ ./Fight.proto --java_out=../java/
 * 生成java文件命令 protoc --proto_path==./ ./Fight.proto --java_out=../java/
 * 通用协议
 * </pre>
 *
 * Protobuf type {@code FightMessage}
 */
public  final class FightMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FightMessage)
    FightMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FightMessage.newBuilder() to construct.
  private FightMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FightMessage() {
    payload_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FightMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            protoId_ = input.readInt32();
            break;
          }
          case 16: {

            order_ = input.readInt32();
            break;
          }
          case 122: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000004;
            }
            payload_.add(input.readBytes());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        payload_ = java.util.Collections.unmodifiableList(payload_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_FightMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_FightMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf2.FightMessage.class, com.mumu.proto.protobuf2.FightMessage.Builder.class);
  }

  private int bitField0_;
  public static final int PROTOID_FIELD_NUMBER = 1;
  private int protoId_;
  /**
   * <pre>
   * 协议Id
   * </pre>
   *
   * <code>int32 protoId = 1;</code>
   */
  public int getProtoId() {
    return protoId_;
  }

  public static final int ORDER_FIELD_NUMBER = 2;
  private int order_;
  /**
   * <pre>
   * 发生的顺序
   * </pre>
   *
   * <code>int32 order = 2;</code>
   */
  public int getOrder() {
    return order_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 15;
  private java.util.List<com.google.protobuf.ByteString> payload_;
  /**
   * <pre>
   * 协议具体内容
   * </pre>
   *
   * <code>repeated bytes payload = 15;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getPayloadList() {
    return payload_;
  }
  /**
   * <pre>
   * 协议具体内容
   * </pre>
   *
   * <code>repeated bytes payload = 15;</code>
   */
  public int getPayloadCount() {
    return payload_.size();
  }
  /**
   * <pre>
   * 协议具体内容
   * </pre>
   *
   * <code>repeated bytes payload = 15;</code>
   */
  public com.google.protobuf.ByteString getPayload(int index) {
    return payload_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (protoId_ != 0) {
      output.writeInt32(1, protoId_);
    }
    if (order_ != 0) {
      output.writeInt32(2, order_);
    }
    for (int i = 0; i < payload_.size(); i++) {
      output.writeBytes(15, payload_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (protoId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, protoId_);
    }
    if (order_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, order_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < payload_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(payload_.get(i));
      }
      size += dataSize;
      size += 1 * getPayloadList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf2.FightMessage)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf2.FightMessage other = (com.mumu.proto.protobuf2.FightMessage) obj;

    if (getProtoId()
        != other.getProtoId()) return false;
    if (getOrder()
        != other.getOrder()) return false;
    if (!getPayloadList()
        .equals(other.getPayloadList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTOID_FIELD_NUMBER;
    hash = (53 * hash) + getProtoId();
    hash = (37 * hash) + ORDER_FIELD_NUMBER;
    hash = (53 * hash) + getOrder();
    if (getPayloadCount() > 0) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.FightMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf2.FightMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 生成java文件命令 protoc -I=./ ./Fight.proto --java_out=../java/
   * 生成java文件命令 protoc --proto_path==./ ./Fight.proto --java_out=../java/
   * 通用协议
   * </pre>
   *
   * Protobuf type {@code FightMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FightMessage)
      com.mumu.proto.protobuf2.FightMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_FightMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_FightMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf2.FightMessage.class, com.mumu.proto.protobuf2.FightMessage.Builder.class);
    }

    // Construct using com.mumu.proto.protobuf2.FightMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      protoId_ = 0;

      order_ = 0;

      payload_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_FightMessage_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.FightMessage getDefaultInstanceForType() {
      return com.mumu.proto.protobuf2.FightMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.FightMessage build() {
      com.mumu.proto.protobuf2.FightMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.FightMessage buildPartial() {
      com.mumu.proto.protobuf2.FightMessage result = new com.mumu.proto.protobuf2.FightMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.protoId_ = protoId_;
      result.order_ = order_;
      if (((bitField0_ & 0x00000004) != 0)) {
        payload_ = java.util.Collections.unmodifiableList(payload_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.payload_ = payload_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf2.FightMessage) {
        return mergeFrom((com.mumu.proto.protobuf2.FightMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf2.FightMessage other) {
      if (other == com.mumu.proto.protobuf2.FightMessage.getDefaultInstance()) return this;
      if (other.getProtoId() != 0) {
        setProtoId(other.getProtoId());
      }
      if (other.getOrder() != 0) {
        setOrder(other.getOrder());
      }
      if (!other.payload_.isEmpty()) {
        if (payload_.isEmpty()) {
          payload_ = other.payload_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensurePayloadIsMutable();
          payload_.addAll(other.payload_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf2.FightMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf2.FightMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int protoId_ ;
    /**
     * <pre>
     * 协议Id
     * </pre>
     *
     * <code>int32 protoId = 1;</code>
     */
    public int getProtoId() {
      return protoId_;
    }
    /**
     * <pre>
     * 协议Id
     * </pre>
     *
     * <code>int32 protoId = 1;</code>
     */
    public Builder setProtoId(int value) {
      
      protoId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议Id
     * </pre>
     *
     * <code>int32 protoId = 1;</code>
     */
    public Builder clearProtoId() {
      
      protoId_ = 0;
      onChanged();
      return this;
    }

    private int order_ ;
    /**
     * <pre>
     * 发生的顺序
     * </pre>
     *
     * <code>int32 order = 2;</code>
     */
    public int getOrder() {
      return order_;
    }
    /**
     * <pre>
     * 发生的顺序
     * </pre>
     *
     * <code>int32 order = 2;</code>
     */
    public Builder setOrder(int value) {
      
      order_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发生的顺序
     * </pre>
     *
     * <code>int32 order = 2;</code>
     */
    public Builder clearOrder() {
      
      order_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> payload_ = java.util.Collections.emptyList();
    private void ensurePayloadIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>(payload_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * 协议具体内容
     * </pre>
     *
     * <code>repeated bytes payload = 15;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPayloadList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(payload_) : payload_;
    }
    /**
     * <pre>
     * 协议具体内容
     * </pre>
     *
     * <code>repeated bytes payload = 15;</code>
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <pre>
     * 协议具体内容
     * </pre>
     *
     * <code>repeated bytes payload = 15;</code>
     */
    public com.google.protobuf.ByteString getPayload(int index) {
      return payload_.get(index);
    }
    /**
     * <pre>
     * 协议具体内容
     * </pre>
     *
     * <code>repeated bytes payload = 15;</code>
     */
    public Builder setPayload(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
      payload_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议具体内容
     * </pre>
     *
     * <code>repeated bytes payload = 15;</code>
     */
    public Builder addPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
      payload_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议具体内容
     * </pre>
     *
     * <code>repeated bytes payload = 15;</code>
     */
    public Builder addAllPayload(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensurePayloadIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, payload_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议具体内容
     * </pre>
     *
     * <code>repeated bytes payload = 15;</code>
     */
    public Builder clearPayload() {
      payload_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FightMessage)
  }

  // @@protoc_insertion_point(class_scope:FightMessage)
  private static final com.mumu.proto.protobuf2.FightMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf2.FightMessage();
  }

  public static com.mumu.proto.protobuf2.FightMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FightMessage>
      PARSER = new com.google.protobuf.AbstractParser<FightMessage>() {
    @java.lang.Override
    public FightMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FightMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FightMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FightMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf2.FightMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

