// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public final class FightMessages {
  private FightMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FightMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FightMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FightFrame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FightFrame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FightReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FightReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AOEDamageMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AOEDamageMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonomerDamageMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonomerDamageMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttackMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AttackMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleEndMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BattleEndMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayersUpdateMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayersUpdateMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResetCdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResetCdMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeAttackTeamMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeAttackTeamMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleFieldMixMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BattleFieldMixMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TeamAttackCDResetMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TeamAttackCDResetMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RageUpdateMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RageUpdateMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerSkillInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerSkillInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TeamSkillInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TeamSkillInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TeamSkillMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TeamSkillMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DisplayMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DisplayMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Fight.proto\"?\n\014FightMessage\022\017\n\007protoId" +
      "\030\001 \001(\005\022\r\n\005order\030\002 \001(\005\022\017\n\007payload\030\017 \003(\014\"Y" +
      "\n\nFightFrame\022\n\n\002id\030\001 \001(\005\022\020\n\010frameNum\030\002 \001" +
      "(\005\022\014\n\004time\030\003 \001(\005\022\037\n\010messages\030\n \003(\0132\r.Fig" +
      "htMessage\"\036\n\013FightReport\022\017\n\007payload\030\001 \003(" +
      "\014\"u\n\020AOEDamageMessage\022\r\n\005attId\030\001 \001(\005\022\016\n\006" +
      "defIds\030\002 \003(\005\022\016\n\006defHps\030\003 \003(\005\022\023\n\013attackTi" +
      "mes\030\004 \001(\005\022\020\n\010damArray\030\005 \003(\005\022\013\n\003hit\030\006 \001(\010" +
      "\"k\n\024MonomerDamageMessage\022\r\n\005attId\030\001 \001(\005\022" +
      "\r\n\005defId\030\002 \001(\005\022\013\n\003dam\030\003 \001(\005\022\r\n\005defHp\030\004 \001" +
      "(\005\022\014\n\004crip\030\005 \001(\010\022\013\n\003hit\030\007 \001(\010\"\200\001\n\rAttack" +
      "Message\022&\n\007monomer\030\001 \001(\0132\025.MonomerDamage" +
      "Message\022\036\n\003aoe\030\002 \001(\0132\021.AOEDamageMessage\022" +
      "\024\n\014shieldOffset\030\003 \001(\005\022\021\n\tdefTeamId\030\004 \001(\005" +
      "\"\036\n\020BattleEndMessage\022\n\n\002id\030\001 \001(\005\"\334\001\n\rPla" +
      "yerMessage\022\n\n\002id\030\001 \001(\005\022\r\n\005index\030\002 \001(\005\022\n\n" +
      "\002lv\030\003 \001(\005\022\014\n\004name\030\004 \001(\t\022\014\n\004type\030\005 \001(\005\022\013\n" +
      "\003pic\030\006 \001(\t\022\017\n\007ability\030\007 \001(\005\022\n\n\002cd\030\010 \001(\005\022" +
      "\r\n\005maxHp\030\t \001(\005\022\n\n\002hp\030\n \001(\005\022\017\n\007troopId\030\013 " +
      "\001(\005\022\021\n\ttroopType\030\014 \001(\005\022\022\n\nreloadTime\030\r \001" +
      "(\005\022\013\n\003pos\030\016 \001(\005\"a\n\024PlayersUpdateMessage\022" +
      "\"\n\naddPlayers\030\001 \003(\0132\016.PlayerMessage\022\025\n\rr" +
      "emovePlayers\030\002 \003(\005\022\016\n\006teamId\030\003 \001(\005\"8\n\016Re" +
      "setCdMessage\022\n\n\002id\030\001 \001(\005\022\n\n\002cd\030\002 \001(\005\022\016\n\006" +
      "teamId\030\003 \001(\005\"Q\n\027ChangeAttackTeamMessage\022" +
      "\021\n\tattTeamId\030\001 \001(\005\022\021\n\tdefTeamId\030\002 \001(\005\022\020\n" +
      "\010reloadCd\030\003 \001(\005\";\n\025BattleFieldMixMessage" +
      "\022\021\n\tsurviveId\030\001 \001(\005\022\017\n\007mixedId\030\002 \001(\005\"6\n\030" +
      "TeamAttackCDResetMessage\022\016\n\006teamId\030\001 \001(\005" +
      "\022\n\n\002cd\030\002 \001(\005\"0\n\021RageUpdateMessage\022\016\n\006tea" +
      "mId\030\001 \001(\005\022\013\n\003num\030\002 \001(\005\":\n\017PlayerSkillInf" +
      "o\022\n\n\002id\030\001 \001(\005\022\014\n\004type\030\002 \001(\005\022\r\n\005value\030\003 \001" +
      "(\005\"Y\n\rTeamSkillInfo\022\016\n\006teamId\030\001 \001(\005\022\"\n\010i" +
      "nfoList\030\002 \003(\0132\020.PlayerSkillInfo\022\024\n\014shiel" +
      "dOffset\030\003 \001(\005\"c\n\020TeamSkillMessage\022\017\n\007ski" +
      "llId\030\001 \001(\005\022\014\n\004step\030\002 \001(\005\022\016\n\006teamId\030\003 \001(\005" +
      "\022 \n\010teamList\030\004 \003(\0132\016.TeamSkillInfo\";\n\016Di" +
      "splayMessage\022\016\n\006teamId\030\001 \001(\005\022\013\n\003num\030\002 \001(" +
      "\005\022\014\n\004type\030\003 \001(\005B+\n\030com.mumu.proto.protob" +
      "uf2B\rFightMessagesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FightMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FightMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FightMessage_descriptor,
        new java.lang.String[] { "ProtoId", "Order", "Payload", });
    internal_static_FightFrame_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FightFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FightFrame_descriptor,
        new java.lang.String[] { "Id", "FrameNum", "Time", "Messages", });
    internal_static_FightReport_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FightReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FightReport_descriptor,
        new java.lang.String[] { "Payload", });
    internal_static_AOEDamageMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AOEDamageMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AOEDamageMessage_descriptor,
        new java.lang.String[] { "AttId", "DefIds", "DefHps", "AttackTimes", "DamArray", "Hit", });
    internal_static_MonomerDamageMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MonomerDamageMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonomerDamageMessage_descriptor,
        new java.lang.String[] { "AttId", "DefId", "Dam", "DefHp", "Crip", "Hit", });
    internal_static_AttackMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AttackMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AttackMessage_descriptor,
        new java.lang.String[] { "Monomer", "Aoe", "ShieldOffset", "DefTeamId", });
    internal_static_BattleEndMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_BattleEndMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BattleEndMessage_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_PlayerMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_PlayerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerMessage_descriptor,
        new java.lang.String[] { "Id", "Index", "Lv", "Name", "Type", "Pic", "Ability", "Cd", "MaxHp", "Hp", "TroopId", "TroopType", "ReloadTime", "Pos", });
    internal_static_PlayersUpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_PlayersUpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayersUpdateMessage_descriptor,
        new java.lang.String[] { "AddPlayers", "RemovePlayers", "TeamId", });
    internal_static_ResetCdMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ResetCdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResetCdMessage_descriptor,
        new java.lang.String[] { "Id", "Cd", "TeamId", });
    internal_static_ChangeAttackTeamMessage_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ChangeAttackTeamMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeAttackTeamMessage_descriptor,
        new java.lang.String[] { "AttTeamId", "DefTeamId", "ReloadCd", });
    internal_static_BattleFieldMixMessage_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_BattleFieldMixMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BattleFieldMixMessage_descriptor,
        new java.lang.String[] { "SurviveId", "MixedId", });
    internal_static_TeamAttackCDResetMessage_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_TeamAttackCDResetMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TeamAttackCDResetMessage_descriptor,
        new java.lang.String[] { "TeamId", "Cd", });
    internal_static_RageUpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_RageUpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RageUpdateMessage_descriptor,
        new java.lang.String[] { "TeamId", "Num", });
    internal_static_PlayerSkillInfo_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_PlayerSkillInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerSkillInfo_descriptor,
        new java.lang.String[] { "Id", "Type", "Value", });
    internal_static_TeamSkillInfo_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_TeamSkillInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TeamSkillInfo_descriptor,
        new java.lang.String[] { "TeamId", "InfoList", "ShieldOffset", });
    internal_static_TeamSkillMessage_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_TeamSkillMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TeamSkillMessage_descriptor,
        new java.lang.String[] { "SkillId", "Step", "TeamId", "TeamList", });
    internal_static_DisplayMessage_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_DisplayMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DisplayMessage_descriptor,
        new java.lang.String[] { "TeamId", "Num", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
