// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface FightMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FightMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 协议Id
   * </pre>
   *
   * <code>int32 protoId = 1;</code>
   */
  int getProtoId();

  /**
   * <pre>
   * 发生的顺序
   * </pre>
   *
   * <code>int32 order = 2;</code>
   */
  int getOrder();

  /**
   * <pre>
   * 协议具体内容
   * </pre>
   *
   * <code>repeated bytes payload = 15;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getPayloadList();
  /**
   * <pre>
   * 协议具体内容
   * </pre>
   *
   * <code>repeated bytes payload = 15;</code>
   */
  int getPayloadCount();
  /**
   * <pre>
   * 协议具体内容
   * </pre>
   *
   * <code>repeated bytes payload = 15;</code>
   */
  com.google.protobuf.ByteString getPayload(int index);
}
