// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

/**
 * <pre>
 * 单体伤害
 * </pre>
 *
 * Protobuf type {@code MonomerDamageMessage}
 */
public  final class MonomerDamageMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MonomerDamageMessage)
    MonomerDamageMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MonomerDamageMessage.newBuilder() to construct.
  private MonomerDamageMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MonomerDamageMessage() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MonomerDamageMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            attId_ = input.readInt32();
            break;
          }
          case 16: {

            defId_ = input.readInt32();
            break;
          }
          case 24: {

            dam_ = input.readInt32();
            break;
          }
          case 32: {

            defHp_ = input.readInt32();
            break;
          }
          case 40: {

            crip_ = input.readBool();
            break;
          }
          case 56: {

            hit_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_MonomerDamageMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_MonomerDamageMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf2.MonomerDamageMessage.class, com.mumu.proto.protobuf2.MonomerDamageMessage.Builder.class);
  }

  public static final int ATTID_FIELD_NUMBER = 1;
  private int attId_;
  /**
   * <pre>
   * 攻击方Id
   * </pre>
   *
   * <code>int32 attId = 1;</code>
   */
  public int getAttId() {
    return attId_;
  }

  public static final int DEFID_FIELD_NUMBER = 2;
  private int defId_;
  /**
   * <pre>
   * 受击方Id
   * </pre>
   *
   * <code>int32 defId = 2;</code>
   */
  public int getDefId() {
    return defId_;
  }

  public static final int DAM_FIELD_NUMBER = 3;
  private int dam_;
  /**
   * <pre>
   * 伤害值
   * </pre>
   *
   * <code>int32 dam = 3;</code>
   */
  public int getDam() {
    return dam_;
  }

  public static final int DEFHP_FIELD_NUMBER = 4;
  private int defHp_;
  /**
   * <pre>
   * 受击方血量
   * </pre>
   *
   * <code>int32 defHp = 4;</code>
   */
  public int getDefHp() {
    return defHp_;
  }

  public static final int CRIP_FIELD_NUMBER = 5;
  private boolean crip_;
  /**
   * <pre>
   * 是否暴击
   * </pre>
   *
   * <code>bool crip = 5;</code>
   */
  public boolean getCrip() {
    return crip_;
  }

  public static final int HIT_FIELD_NUMBER = 7;
  private boolean hit_;
  /**
   * <pre>
   * 是否命中目标
   * </pre>
   *
   * <code>bool hit = 7;</code>
   */
  public boolean getHit() {
    return hit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (attId_ != 0) {
      output.writeInt32(1, attId_);
    }
    if (defId_ != 0) {
      output.writeInt32(2, defId_);
    }
    if (dam_ != 0) {
      output.writeInt32(3, dam_);
    }
    if (defHp_ != 0) {
      output.writeInt32(4, defHp_);
    }
    if (crip_ != false) {
      output.writeBool(5, crip_);
    }
    if (hit_ != false) {
      output.writeBool(7, hit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (attId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, attId_);
    }
    if (defId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, defId_);
    }
    if (dam_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, dam_);
    }
    if (defHp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, defHp_);
    }
    if (crip_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, crip_);
    }
    if (hit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, hit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf2.MonomerDamageMessage)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf2.MonomerDamageMessage other = (com.mumu.proto.protobuf2.MonomerDamageMessage) obj;

    if (getAttId()
        != other.getAttId()) return false;
    if (getDefId()
        != other.getDefId()) return false;
    if (getDam()
        != other.getDam()) return false;
    if (getDefHp()
        != other.getDefHp()) return false;
    if (getCrip()
        != other.getCrip()) return false;
    if (getHit()
        != other.getHit()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ATTID_FIELD_NUMBER;
    hash = (53 * hash) + getAttId();
    hash = (37 * hash) + DEFID_FIELD_NUMBER;
    hash = (53 * hash) + getDefId();
    hash = (37 * hash) + DAM_FIELD_NUMBER;
    hash = (53 * hash) + getDam();
    hash = (37 * hash) + DEFHP_FIELD_NUMBER;
    hash = (53 * hash) + getDefHp();
    hash = (37 * hash) + CRIP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCrip());
    hash = (37 * hash) + HIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHit());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.MonomerDamageMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf2.MonomerDamageMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 单体伤害
   * </pre>
   *
   * Protobuf type {@code MonomerDamageMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MonomerDamageMessage)
      com.mumu.proto.protobuf2.MonomerDamageMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_MonomerDamageMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_MonomerDamageMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf2.MonomerDamageMessage.class, com.mumu.proto.protobuf2.MonomerDamageMessage.Builder.class);
    }

    // Construct using com.mumu.proto.protobuf2.MonomerDamageMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      attId_ = 0;

      defId_ = 0;

      dam_ = 0;

      defHp_ = 0;

      crip_ = false;

      hit_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_MonomerDamageMessage_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.MonomerDamageMessage getDefaultInstanceForType() {
      return com.mumu.proto.protobuf2.MonomerDamageMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.MonomerDamageMessage build() {
      com.mumu.proto.protobuf2.MonomerDamageMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.MonomerDamageMessage buildPartial() {
      com.mumu.proto.protobuf2.MonomerDamageMessage result = new com.mumu.proto.protobuf2.MonomerDamageMessage(this);
      result.attId_ = attId_;
      result.defId_ = defId_;
      result.dam_ = dam_;
      result.defHp_ = defHp_;
      result.crip_ = crip_;
      result.hit_ = hit_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf2.MonomerDamageMessage) {
        return mergeFrom((com.mumu.proto.protobuf2.MonomerDamageMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf2.MonomerDamageMessage other) {
      if (other == com.mumu.proto.protobuf2.MonomerDamageMessage.getDefaultInstance()) return this;
      if (other.getAttId() != 0) {
        setAttId(other.getAttId());
      }
      if (other.getDefId() != 0) {
        setDefId(other.getDefId());
      }
      if (other.getDam() != 0) {
        setDam(other.getDam());
      }
      if (other.getDefHp() != 0) {
        setDefHp(other.getDefHp());
      }
      if (other.getCrip() != false) {
        setCrip(other.getCrip());
      }
      if (other.getHit() != false) {
        setHit(other.getHit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf2.MonomerDamageMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf2.MonomerDamageMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int attId_ ;
    /**
     * <pre>
     * 攻击方Id
     * </pre>
     *
     * <code>int32 attId = 1;</code>
     */
    public int getAttId() {
      return attId_;
    }
    /**
     * <pre>
     * 攻击方Id
     * </pre>
     *
     * <code>int32 attId = 1;</code>
     */
    public Builder setAttId(int value) {
      
      attId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 攻击方Id
     * </pre>
     *
     * <code>int32 attId = 1;</code>
     */
    public Builder clearAttId() {
      
      attId_ = 0;
      onChanged();
      return this;
    }

    private int defId_ ;
    /**
     * <pre>
     * 受击方Id
     * </pre>
     *
     * <code>int32 defId = 2;</code>
     */
    public int getDefId() {
      return defId_;
    }
    /**
     * <pre>
     * 受击方Id
     * </pre>
     *
     * <code>int32 defId = 2;</code>
     */
    public Builder setDefId(int value) {
      
      defId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方Id
     * </pre>
     *
     * <code>int32 defId = 2;</code>
     */
    public Builder clearDefId() {
      
      defId_ = 0;
      onChanged();
      return this;
    }

    private int dam_ ;
    /**
     * <pre>
     * 伤害值
     * </pre>
     *
     * <code>int32 dam = 3;</code>
     */
    public int getDam() {
      return dam_;
    }
    /**
     * <pre>
     * 伤害值
     * </pre>
     *
     * <code>int32 dam = 3;</code>
     */
    public Builder setDam(int value) {
      
      dam_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 伤害值
     * </pre>
     *
     * <code>int32 dam = 3;</code>
     */
    public Builder clearDam() {
      
      dam_ = 0;
      onChanged();
      return this;
    }

    private int defHp_ ;
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>int32 defHp = 4;</code>
     */
    public int getDefHp() {
      return defHp_;
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>int32 defHp = 4;</code>
     */
    public Builder setDefHp(int value) {
      
      defHp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 受击方血量
     * </pre>
     *
     * <code>int32 defHp = 4;</code>
     */
    public Builder clearDefHp() {
      
      defHp_ = 0;
      onChanged();
      return this;
    }

    private boolean crip_ ;
    /**
     * <pre>
     * 是否暴击
     * </pre>
     *
     * <code>bool crip = 5;</code>
     */
    public boolean getCrip() {
      return crip_;
    }
    /**
     * <pre>
     * 是否暴击
     * </pre>
     *
     * <code>bool crip = 5;</code>
     */
    public Builder setCrip(boolean value) {
      
      crip_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否暴击
     * </pre>
     *
     * <code>bool crip = 5;</code>
     */
    public Builder clearCrip() {
      
      crip_ = false;
      onChanged();
      return this;
    }

    private boolean hit_ ;
    /**
     * <pre>
     * 是否命中目标
     * </pre>
     *
     * <code>bool hit = 7;</code>
     */
    public boolean getHit() {
      return hit_;
    }
    /**
     * <pre>
     * 是否命中目标
     * </pre>
     *
     * <code>bool hit = 7;</code>
     */
    public Builder setHit(boolean value) {
      
      hit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否命中目标
     * </pre>
     *
     * <code>bool hit = 7;</code>
     */
    public Builder clearHit() {
      
      hit_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MonomerDamageMessage)
  }

  // @@protoc_insertion_point(class_scope:MonomerDamageMessage)
  private static final com.mumu.proto.protobuf2.MonomerDamageMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf2.MonomerDamageMessage();
  }

  public static com.mumu.proto.protobuf2.MonomerDamageMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MonomerDamageMessage>
      PARSER = new com.google.protobuf.AbstractParser<MonomerDamageMessage>() {
    @java.lang.Override
    public MonomerDamageMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MonomerDamageMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MonomerDamageMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MonomerDamageMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf2.MonomerDamageMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

