// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface PlayerSkillInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerSkillInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 小兵id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   * 影响类型
   * </pre>
   *
   * <code>int32 type = 2;</code>
   */
  int getType();

  /**
   * <pre>
   * 数值
   * </pre>
   *
   * <code>int32 value = 3;</code>
   */
  int getValue();
}
