// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface PlayersUpdateMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayersUpdateMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 新增的小兵
   * </pre>
   *
   * <code>repeated .PlayerMessage addPlayers = 1;</code>
   */
  java.util.List<com.mumu.proto.protobuf2.PlayerMessage> 
      getAddPlayersList();
  /**
   * <pre>
   * 新增的小兵
   * </pre>
   *
   * <code>repeated .PlayerMessage addPlayers = 1;</code>
   */
  com.mumu.proto.protobuf2.PlayerMessage getAddPlayers(int index);
  /**
   * <pre>
   * 新增的小兵
   * </pre>
   *
   * <code>repeated .PlayerMessage addPlayers = 1;</code>
   */
  int getAddPlayersCount();
  /**
   * <pre>
   * 新增的小兵
   * </pre>
   *
   * <code>repeated .PlayerMessage addPlayers = 1;</code>
   */
  java.util.List<? extends com.mumu.proto.protobuf2.PlayerMessageOrBuilder> 
      getAddPlayersOrBuilderList();
  /**
   * <pre>
   * 新增的小兵
   * </pre>
   *
   * <code>repeated .PlayerMessage addPlayers = 1;</code>
   */
  com.mumu.proto.protobuf2.PlayerMessageOrBuilder getAddPlayersOrBuilder(
      int index);

  /**
   * <pre>
   * 被删除的小兵
   * </pre>
   *
   * <code>repeated int32 removePlayers = 2;</code>
   */
  java.util.List<java.lang.Integer> getRemovePlayersList();
  /**
   * <pre>
   * 被删除的小兵
   * </pre>
   *
   * <code>repeated int32 removePlayers = 2;</code>
   */
  int getRemovePlayersCount();
  /**
   * <pre>
   * 被删除的小兵
   * </pre>
   *
   * <code>repeated int32 removePlayers = 2;</code>
   */
  int getRemovePlayers(int index);

  /**
   * <pre>
   * 编队id
   * </pre>
   *
   * <code>int32 teamId = 3;</code>
   */
  int getTeamId();
}
