// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface PlayerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 主体Id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   * 下标
   * </pre>
   *
   * <code>int32 index = 2;</code>
   */
  int getIndex();

  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>int32 lv = 3;</code>
   */
  int getLv();

  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 类型
   * </pre>
   *
   * <code>int32 type = 5;</code>
   */
  int getType();

  /**
   * <pre>
   * 图片
   * </pre>
   *
   * <code>string pic = 6;</code>
   */
  java.lang.String getPic();
  /**
   * <pre>
   * 图片
   * </pre>
   *
   * <code>string pic = 6;</code>
   */
  com.google.protobuf.ByteString
      getPicBytes();

  /**
   * <pre>
   * 战力
   * </pre>
   *
   * <code>int32 ability = 7;</code>
   */
  int getAbility();

  /**
   * <pre>
   * cd
   * </pre>
   *
   * <code>int32 cd = 8;</code>
   */
  int getCd();

  /**
   * <pre>
   * 最大血量
   * </pre>
   *
   * <code>int32 maxHp = 9;</code>
   */
  int getMaxHp();

  /**
   * <pre>
   * 当前血量
   * </pre>
   *
   * <code>int32 hp = 10;</code>
   */
  int getHp();

  /**
   * <pre>
   * 编队id
   * </pre>
   *
   * <code>int32 troopId = 11;</code>
   */
  int getTroopId();

  /**
   * <pre>
   * 编队类型
   * </pre>
   *
   * <code>int32 troopType = 12;</code>
   */
  int getTroopType();

  /**
   * <pre>
   * 填弹时间
   * </pre>
   *
   * <code>int32 reloadTime = 13;</code>
   */
  int getReloadTime();

  /**
   * <pre>
   * 子队在编队中的位置 (1开始)
   * </pre>
   *
   * <code>int32 pos = 14;</code>
   */
  int getPos();
}
