// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface TeamAttackCDResetMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TeamAttackCDResetMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 部队id
   * </pre>
   *
   * <code>int32 teamId = 1;</code>
   */
  int getTeamId();

  /**
   * <pre>
   * 攻击cd
   * </pre>
   *
   * <code>int32 cd = 2;</code>
   */
  int getCd();
}
