// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

public interface TeamSkillInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TeamSkillInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 编队id
   * </pre>
   *
   * <code>int32 teamId = 1;</code>
   */
  int getTeamId();

  /**
   * <pre>
   * 编队中受到技能影响
   * </pre>
   *
   * <code>repeated .PlayerSkillInfo infoList = 2;</code>
   */
  java.util.List<com.mumu.proto.protobuf2.PlayerSkillInfo> 
      getInfoListList();
  /**
   * <pre>
   * 编队中受到技能影响
   * </pre>
   *
   * <code>repeated .PlayerSkillInfo infoList = 2;</code>
   */
  com.mumu.proto.protobuf2.PlayerSkillInfo getInfoList(int index);
  /**
   * <pre>
   * 编队中受到技能影响
   * </pre>
   *
   * <code>repeated .PlayerSkillInfo infoList = 2;</code>
   */
  int getInfoListCount();
  /**
   * <pre>
   * 编队中受到技能影响
   * </pre>
   *
   * <code>repeated .PlayerSkillInfo infoList = 2;</code>
   */
  java.util.List<? extends com.mumu.proto.protobuf2.PlayerSkillInfoOrBuilder> 
      getInfoListOrBuilderList();
  /**
   * <pre>
   * 编队中受到技能影响
   * </pre>
   *
   * <code>repeated .PlayerSkillInfo infoList = 2;</code>
   */
  com.mumu.proto.protobuf2.PlayerSkillInfoOrBuilder getInfoListOrBuilder(
      int index);

  /**
   * <pre>
   * 护盾吸收伤害
   * </pre>
   *
   * <code>int32 shieldOffset = 3;</code>
   */
  int getShieldOffset();
}
