// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.mumu.proto.protobuf2;

/**
 * <pre>
 * 技能协议 ProtoId 9
 * </pre>
 *
 * Protobuf type {@code TeamSkillMessage}
 */
public  final class TeamSkillMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TeamSkillMessage)
    TeamSkillMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TeamSkillMessage.newBuilder() to construct.
  private TeamSkillMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TeamSkillMessage() {
    teamList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TeamSkillMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            skillId_ = input.readInt32();
            break;
          }
          case 16: {

            step_ = input.readInt32();
            break;
          }
          case 24: {

            teamId_ = input.readInt32();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              teamList_ = new java.util.ArrayList<com.mumu.proto.protobuf2.TeamSkillInfo>();
              mutable_bitField0_ |= 0x00000008;
            }
            teamList_.add(
                input.readMessage(com.mumu.proto.protobuf2.TeamSkillInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        teamList_ = java.util.Collections.unmodifiableList(teamList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_TeamSkillMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf2.FightMessages.internal_static_TeamSkillMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf2.TeamSkillMessage.class, com.mumu.proto.protobuf2.TeamSkillMessage.Builder.class);
  }

  private int bitField0_;
  public static final int SKILLID_FIELD_NUMBER = 1;
  private int skillId_;
  /**
   * <pre>
   * 技能id
   * </pre>
   *
   * <code>int32 skillId = 1;</code>
   */
  public int getSkillId() {
    return skillId_;
  }

  public static final int STEP_FIELD_NUMBER = 2;
  private int step_;
  /**
   * <pre>
   * 技能阶段
   * </pre>
   *
   * <code>int32 step = 2;</code>
   */
  public int getStep() {
    return step_;
  }

  public static final int TEAMID_FIELD_NUMBER = 3;
  private int teamId_;
  /**
   * <pre>
   * 释放技能的编队id
   * </pre>
   *
   * <code>int32 teamId = 3;</code>
   */
  public int getTeamId() {
    return teamId_;
  }

  public static final int TEAMLIST_FIELD_NUMBER = 4;
  private java.util.List<com.mumu.proto.protobuf2.TeamSkillInfo> teamList_;
  /**
   * <pre>
   * 受技能影响的编队
   * </pre>
   *
   * <code>repeated .TeamSkillInfo teamList = 4;</code>
   */
  public java.util.List<com.mumu.proto.protobuf2.TeamSkillInfo> getTeamListList() {
    return teamList_;
  }
  /**
   * <pre>
   * 受技能影响的编队
   * </pre>
   *
   * <code>repeated .TeamSkillInfo teamList = 4;</code>
   */
  public java.util.List<? extends com.mumu.proto.protobuf2.TeamSkillInfoOrBuilder> 
      getTeamListOrBuilderList() {
    return teamList_;
  }
  /**
   * <pre>
   * 受技能影响的编队
   * </pre>
   *
   * <code>repeated .TeamSkillInfo teamList = 4;</code>
   */
  public int getTeamListCount() {
    return teamList_.size();
  }
  /**
   * <pre>
   * 受技能影响的编队
   * </pre>
   *
   * <code>repeated .TeamSkillInfo teamList = 4;</code>
   */
  public com.mumu.proto.protobuf2.TeamSkillInfo getTeamList(int index) {
    return teamList_.get(index);
  }
  /**
   * <pre>
   * 受技能影响的编队
   * </pre>
   *
   * <code>repeated .TeamSkillInfo teamList = 4;</code>
   */
  public com.mumu.proto.protobuf2.TeamSkillInfoOrBuilder getTeamListOrBuilder(
      int index) {
    return teamList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (skillId_ != 0) {
      output.writeInt32(1, skillId_);
    }
    if (step_ != 0) {
      output.writeInt32(2, step_);
    }
    if (teamId_ != 0) {
      output.writeInt32(3, teamId_);
    }
    for (int i = 0; i < teamList_.size(); i++) {
      output.writeMessage(4, teamList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (skillId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, skillId_);
    }
    if (step_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, step_);
    }
    if (teamId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, teamId_);
    }
    for (int i = 0; i < teamList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, teamList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf2.TeamSkillMessage)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf2.TeamSkillMessage other = (com.mumu.proto.protobuf2.TeamSkillMessage) obj;

    if (getSkillId()
        != other.getSkillId()) return false;
    if (getStep()
        != other.getStep()) return false;
    if (getTeamId()
        != other.getTeamId()) return false;
    if (!getTeamListList()
        .equals(other.getTeamListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKILLID_FIELD_NUMBER;
    hash = (53 * hash) + getSkillId();
    hash = (37 * hash) + STEP_FIELD_NUMBER;
    hash = (53 * hash) + getStep();
    hash = (37 * hash) + TEAMID_FIELD_NUMBER;
    hash = (53 * hash) + getTeamId();
    if (getTeamListCount() > 0) {
      hash = (37 * hash) + TEAMLIST_FIELD_NUMBER;
      hash = (53 * hash) + getTeamListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf2.TeamSkillMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf2.TeamSkillMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 技能协议 ProtoId 9
   * </pre>
   *
   * Protobuf type {@code TeamSkillMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TeamSkillMessage)
      com.mumu.proto.protobuf2.TeamSkillMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_TeamSkillMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_TeamSkillMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf2.TeamSkillMessage.class, com.mumu.proto.protobuf2.TeamSkillMessage.Builder.class);
    }

    // Construct using com.mumu.proto.protobuf2.TeamSkillMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTeamListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      skillId_ = 0;

      step_ = 0;

      teamId_ = 0;

      if (teamListBuilder_ == null) {
        teamList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        teamListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf2.FightMessages.internal_static_TeamSkillMessage_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.TeamSkillMessage getDefaultInstanceForType() {
      return com.mumu.proto.protobuf2.TeamSkillMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.TeamSkillMessage build() {
      com.mumu.proto.protobuf2.TeamSkillMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf2.TeamSkillMessage buildPartial() {
      com.mumu.proto.protobuf2.TeamSkillMessage result = new com.mumu.proto.protobuf2.TeamSkillMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.skillId_ = skillId_;
      result.step_ = step_;
      result.teamId_ = teamId_;
      if (teamListBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          teamList_ = java.util.Collections.unmodifiableList(teamList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.teamList_ = teamList_;
      } else {
        result.teamList_ = teamListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf2.TeamSkillMessage) {
        return mergeFrom((com.mumu.proto.protobuf2.TeamSkillMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf2.TeamSkillMessage other) {
      if (other == com.mumu.proto.protobuf2.TeamSkillMessage.getDefaultInstance()) return this;
      if (other.getSkillId() != 0) {
        setSkillId(other.getSkillId());
      }
      if (other.getStep() != 0) {
        setStep(other.getStep());
      }
      if (other.getTeamId() != 0) {
        setTeamId(other.getTeamId());
      }
      if (teamListBuilder_ == null) {
        if (!other.teamList_.isEmpty()) {
          if (teamList_.isEmpty()) {
            teamList_ = other.teamList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTeamListIsMutable();
            teamList_.addAll(other.teamList_);
          }
          onChanged();
        }
      } else {
        if (!other.teamList_.isEmpty()) {
          if (teamListBuilder_.isEmpty()) {
            teamListBuilder_.dispose();
            teamListBuilder_ = null;
            teamList_ = other.teamList_;
            bitField0_ = (bitField0_ & ~0x00000008);
            teamListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTeamListFieldBuilder() : null;
          } else {
            teamListBuilder_.addAllMessages(other.teamList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf2.TeamSkillMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf2.TeamSkillMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int skillId_ ;
    /**
     * <pre>
     * 技能id
     * </pre>
     *
     * <code>int32 skillId = 1;</code>
     */
    public int getSkillId() {
      return skillId_;
    }
    /**
     * <pre>
     * 技能id
     * </pre>
     *
     * <code>int32 skillId = 1;</code>
     */
    public Builder setSkillId(int value) {
      
      skillId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 技能id
     * </pre>
     *
     * <code>int32 skillId = 1;</code>
     */
    public Builder clearSkillId() {
      
      skillId_ = 0;
      onChanged();
      return this;
    }

    private int step_ ;
    /**
     * <pre>
     * 技能阶段
     * </pre>
     *
     * <code>int32 step = 2;</code>
     */
    public int getStep() {
      return step_;
    }
    /**
     * <pre>
     * 技能阶段
     * </pre>
     *
     * <code>int32 step = 2;</code>
     */
    public Builder setStep(int value) {
      
      step_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 技能阶段
     * </pre>
     *
     * <code>int32 step = 2;</code>
     */
    public Builder clearStep() {
      
      step_ = 0;
      onChanged();
      return this;
    }

    private int teamId_ ;
    /**
     * <pre>
     * 释放技能的编队id
     * </pre>
     *
     * <code>int32 teamId = 3;</code>
     */
    public int getTeamId() {
      return teamId_;
    }
    /**
     * <pre>
     * 释放技能的编队id
     * </pre>
     *
     * <code>int32 teamId = 3;</code>
     */
    public Builder setTeamId(int value) {
      
      teamId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 释放技能的编队id
     * </pre>
     *
     * <code>int32 teamId = 3;</code>
     */
    public Builder clearTeamId() {
      
      teamId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.mumu.proto.protobuf2.TeamSkillInfo> teamList_ =
      java.util.Collections.emptyList();
    private void ensureTeamListIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        teamList_ = new java.util.ArrayList<com.mumu.proto.protobuf2.TeamSkillInfo>(teamList_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mumu.proto.protobuf2.TeamSkillInfo, com.mumu.proto.protobuf2.TeamSkillInfo.Builder, com.mumu.proto.protobuf2.TeamSkillInfoOrBuilder> teamListBuilder_;

    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public java.util.List<com.mumu.proto.protobuf2.TeamSkillInfo> getTeamListList() {
      if (teamListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(teamList_);
      } else {
        return teamListBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public int getTeamListCount() {
      if (teamListBuilder_ == null) {
        return teamList_.size();
      } else {
        return teamListBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public com.mumu.proto.protobuf2.TeamSkillInfo getTeamList(int index) {
      if (teamListBuilder_ == null) {
        return teamList_.get(index);
      } else {
        return teamListBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder setTeamList(
        int index, com.mumu.proto.protobuf2.TeamSkillInfo value) {
      if (teamListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeamListIsMutable();
        teamList_.set(index, value);
        onChanged();
      } else {
        teamListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder setTeamList(
        int index, com.mumu.proto.protobuf2.TeamSkillInfo.Builder builderForValue) {
      if (teamListBuilder_ == null) {
        ensureTeamListIsMutable();
        teamList_.set(index, builderForValue.build());
        onChanged();
      } else {
        teamListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder addTeamList(com.mumu.proto.protobuf2.TeamSkillInfo value) {
      if (teamListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeamListIsMutable();
        teamList_.add(value);
        onChanged();
      } else {
        teamListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder addTeamList(
        int index, com.mumu.proto.protobuf2.TeamSkillInfo value) {
      if (teamListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeamListIsMutable();
        teamList_.add(index, value);
        onChanged();
      } else {
        teamListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder addTeamList(
        com.mumu.proto.protobuf2.TeamSkillInfo.Builder builderForValue) {
      if (teamListBuilder_ == null) {
        ensureTeamListIsMutable();
        teamList_.add(builderForValue.build());
        onChanged();
      } else {
        teamListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder addTeamList(
        int index, com.mumu.proto.protobuf2.TeamSkillInfo.Builder builderForValue) {
      if (teamListBuilder_ == null) {
        ensureTeamListIsMutable();
        teamList_.add(index, builderForValue.build());
        onChanged();
      } else {
        teamListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder addAllTeamList(
        java.lang.Iterable<? extends com.mumu.proto.protobuf2.TeamSkillInfo> values) {
      if (teamListBuilder_ == null) {
        ensureTeamListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, teamList_);
        onChanged();
      } else {
        teamListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder clearTeamList() {
      if (teamListBuilder_ == null) {
        teamList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        teamListBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public Builder removeTeamList(int index) {
      if (teamListBuilder_ == null) {
        ensureTeamListIsMutable();
        teamList_.remove(index);
        onChanged();
      } else {
        teamListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public com.mumu.proto.protobuf2.TeamSkillInfo.Builder getTeamListBuilder(
        int index) {
      return getTeamListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public com.mumu.proto.protobuf2.TeamSkillInfoOrBuilder getTeamListOrBuilder(
        int index) {
      if (teamListBuilder_ == null) {
        return teamList_.get(index);  } else {
        return teamListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public java.util.List<? extends com.mumu.proto.protobuf2.TeamSkillInfoOrBuilder> 
         getTeamListOrBuilderList() {
      if (teamListBuilder_ != null) {
        return teamListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(teamList_);
      }
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public com.mumu.proto.protobuf2.TeamSkillInfo.Builder addTeamListBuilder() {
      return getTeamListFieldBuilder().addBuilder(
          com.mumu.proto.protobuf2.TeamSkillInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public com.mumu.proto.protobuf2.TeamSkillInfo.Builder addTeamListBuilder(
        int index) {
      return getTeamListFieldBuilder().addBuilder(
          index, com.mumu.proto.protobuf2.TeamSkillInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 受技能影响的编队
     * </pre>
     *
     * <code>repeated .TeamSkillInfo teamList = 4;</code>
     */
    public java.util.List<com.mumu.proto.protobuf2.TeamSkillInfo.Builder> 
         getTeamListBuilderList() {
      return getTeamListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mumu.proto.protobuf2.TeamSkillInfo, com.mumu.proto.protobuf2.TeamSkillInfo.Builder, com.mumu.proto.protobuf2.TeamSkillInfoOrBuilder> 
        getTeamListFieldBuilder() {
      if (teamListBuilder_ == null) {
        teamListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mumu.proto.protobuf2.TeamSkillInfo, com.mumu.proto.protobuf2.TeamSkillInfo.Builder, com.mumu.proto.protobuf2.TeamSkillInfoOrBuilder>(
                teamList_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        teamList_ = null;
      }
      return teamListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TeamSkillMessage)
  }

  // @@protoc_insertion_point(class_scope:TeamSkillMessage)
  private static final com.mumu.proto.protobuf2.TeamSkillMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf2.TeamSkillMessage();
  }

  public static com.mumu.proto.protobuf2.TeamSkillMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TeamSkillMessage>
      PARSER = new com.google.protobuf.AbstractParser<TeamSkillMessage>() {
    @java.lang.Override
    public TeamSkillMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TeamSkillMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TeamSkillMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TeamSkillMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf2.TeamSkillMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

