// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JetProtos.proto

package com.mumu.proto.protobuf;

/**
 * Protobuf type {@code PersonTest}
 */
public  final class PersonTest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PersonTest)
    PersonTestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonTest.newBuilder() to construct.
  private PersonTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonTest() {
    name_ = "";
    email_ = "";
    sex_ = 0;
    phone_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersonTest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            sex_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              phone_ = new java.util.ArrayList<com.mumu.proto.protobuf.PersonTest.PhoneNumber>();
              mutable_bitField0_ |= 0x00000010;
            }
            phone_.add(
                input.readMessage(com.mumu.proto.protobuf.PersonTest.PhoneNumber.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              tags_ = com.google.protobuf.MapField.newMapField(
                  TagsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            tags__ = input.readMessage(
                TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            tags_.getMutableMap().put(
                tags__.getKey(), tags__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        phone_ = java.util.Collections.unmodifiableList(phone_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetTags();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.proto.protobuf.PersonTest.class, com.mumu.proto.protobuf.PersonTest.Builder.class);
  }

  /**
   * <pre>
   * 定义一个枚举
   * </pre>
   *
   * Protobuf enum {@code PersonTest.Sex}
   */
  public enum Sex
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT = 0;</code>
     */
    DEFAULT(0),
    /**
     * <code>MALE = 1;</code>
     */
    MALE(1),
    /**
     * <code>Female = 2;</code>
     */
    Female(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT = 0;</code>
     */
    public static final int DEFAULT_VALUE = 0;
    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;
    /**
     * <code>Female = 2;</code>
     */
    public static final int Female_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Sex valueOf(int value) {
      return forNumber(value);
    }

    public static Sex forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT;
        case 1: return MALE;
        case 2: return Female;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sex>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sex> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
            public Sex findValueByNumber(int number) {
              return Sex.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mumu.proto.protobuf.PersonTest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Sex[] VALUES = values();

    public static Sex valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sex(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PersonTest.Sex)
  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PersonTest.PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
     */
    com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType getType();
  }
  /**
   * <pre>
   * 定义一个 message
   * </pre>
   *
   * Protobuf type {@code PersonTest.PhoneNumber}
   */
  public  static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PersonTest.PhoneNumber)
      PhoneNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf.PersonTest.PhoneNumber.class, com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder.class);
    }

    /**
     * Protobuf enum {@code PersonTest.PhoneNumber.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mumu.proto.protobuf.PersonTest.PhoneNumber.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PersonTest.PhoneNumber.PhoneType)
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>string number = 1;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
     */
    public com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType getType() {
      @SuppressWarnings("deprecation")
      com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType result = com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType.valueOf(type_);
      return result == null ? com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (type_ != com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType.MOBILE.getNumber()) {
        output.writeEnum(2, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (type_ != com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mumu.proto.protobuf.PersonTest.PhoneNumber)) {
        return super.equals(obj);
      }
      com.mumu.proto.protobuf.PersonTest.PhoneNumber other = (com.mumu.proto.protobuf.PersonTest.PhoneNumber) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mumu.proto.protobuf.PersonTest.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义一个 message
     * </pre>
     *
     * Protobuf type {@code PersonTest.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PersonTest.PhoneNumber)
        com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mumu.proto.protobuf.PersonTest.PhoneNumber.class, com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder.class);
      }

      // Construct using com.gobestsoft.proto.protobuf.PersonTest.PhoneNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public com.mumu.proto.protobuf.PersonTest.PhoneNumber getDefaultInstanceForType() {
        return com.mumu.proto.protobuf.PersonTest.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public com.mumu.proto.protobuf.PersonTest.PhoneNumber build() {
        com.mumu.proto.protobuf.PersonTest.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mumu.proto.protobuf.PersonTest.PhoneNumber buildPartial() {
        com.mumu.proto.protobuf.PersonTest.PhoneNumber result = new com.mumu.proto.protobuf.PersonTest.PhoneNumber(this);
        result.number_ = number_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mumu.proto.protobuf.PersonTest.PhoneNumber) {
          return mergeFrom((com.mumu.proto.protobuf.PersonTest.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mumu.proto.protobuf.PersonTest.PhoneNumber other) {
        if (other == com.mumu.proto.protobuf.PersonTest.PhoneNumber.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mumu.proto.protobuf.PersonTest.PhoneNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mumu.proto.protobuf.PersonTest.PhoneNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
       */
      public com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType getType() {
        @SuppressWarnings("deprecation")
        com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType result = com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType.valueOf(type_);
        return result == null ? com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
       */
      public Builder setType(com.mumu.proto.protobuf.PersonTest.PhoneNumber.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.PersonTest.PhoneNumber.PhoneType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PersonTest.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:PersonTest.PhoneNumber)
    private static final com.mumu.proto.protobuf.PersonTest.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mumu.proto.protobuf.PersonTest.PhoneNumber();
    }

    public static com.mumu.proto.protobuf.PersonTest.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf.PersonTest.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <pre>
   * int 类型
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 3;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEX_FIELD_NUMBER = 4;
  private int sex_;
  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.PersonTest.Sex sex = 4;</code>
   */
  public int getSexValue() {
    return sex_;
  }
  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * <code>.PersonTest.Sex sex = 4;</code>
   */
  public com.mumu.proto.protobuf.PersonTest.Sex getSex() {
    @SuppressWarnings("deprecation")
    com.mumu.proto.protobuf.PersonTest.Sex result = com.mumu.proto.protobuf.PersonTest.Sex.valueOf(sex_);
    return result == null ? com.mumu.proto.protobuf.PersonTest.Sex.UNRECOGNIZED : result;
  }

  public static final int PHONE_FIELD_NUMBER = 5;
  private java.util.List<com.mumu.proto.protobuf.PersonTest.PhoneNumber> phone_;
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  public java.util.List<com.mumu.proto.protobuf.PersonTest.PhoneNumber> getPhoneList() {
    return phone_;
  }
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  public java.util.List<? extends com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder>
      getPhoneOrBuilderList() {
    return phone_;
  }
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  public int getPhoneCount() {
    return phone_.size();
  }
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  public com.mumu.proto.protobuf.PersonTest.PhoneNumber getPhone(int index) {
    return phone_.get(index);
  }
  /**
   * <pre>
   * 引用下面定义的 PhoneNumber 类型的 message
   * </pre>
   *
   * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
   */
  public com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index) {
    return phone_.get(index);
  }

  public static final int TAGS_FIELD_NUMBER = 6;
  private static final class TagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_TagsEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> tags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTags() {
    if (tags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TagsDefaultEntryHolder.defaultEntry);
    }
    return tags_;
  }

  public int getTagsCount() {
    return internalGetTags().getMap().size();
  }
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  public boolean containsTags(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTags() {
    return getTagsMap();
  }
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
    return internalGetTags().getMap();
  }
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  public java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * map 类型
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 6;</code>
   */

  public java.lang.String getTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (sex_ != com.mumu.proto.protobuf.PersonTest.Sex.DEFAULT.getNumber()) {
      output.writeEnum(4, sex_);
    }
    for (int i = 0; i < phone_.size(); i++) {
      output.writeMessage(5, phone_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTags(),
        TagsDefaultEntryHolder.defaultEntry,
        6);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (sex_ != com.mumu.proto.protobuf.PersonTest.Sex.DEFAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, sex_);
    }
    for (int i = 0; i < phone_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, phone_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, tags__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.proto.protobuf.PersonTest)) {
      return super.equals(obj);
    }
    com.mumu.proto.protobuf.PersonTest other = (com.mumu.proto.protobuf.PersonTest) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (sex_ != other.sex_) return false;
    if (!getPhoneList()
        .equals(other.getPhoneList())) return false;
    if (!internalGetTags().equals(
        other.internalGetTags())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + SEX_FIELD_NUMBER;
    hash = (53 * hash) + sex_;
    if (getPhoneCount() > 0) {
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneList().hashCode();
    }
    if (!internalGetTags().getMap().isEmpty()) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTags().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf.PersonTest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf.PersonTest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.proto.protobuf.PersonTest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.proto.protobuf.PersonTest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PersonTest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PersonTest)
      com.mumu.proto.protobuf.PersonTestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.proto.protobuf.PersonTest.class, com.mumu.proto.protobuf.PersonTest.Builder.class);
    }

    // Construct using com.gobestsoft.proto.protobuf.PersonTest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhoneFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      email_ = "";

      sex_ = 0;

      if (phoneBuilder_ == null) {
        phone_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        phoneBuilder_.clear();
      }
      internalGetMutableTags().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.proto.protobuf.PersonTestProtos.internal_static_PersonTest_descriptor;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf.PersonTest getDefaultInstanceForType() {
      return com.mumu.proto.protobuf.PersonTest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.proto.protobuf.PersonTest build() {
      com.mumu.proto.protobuf.PersonTest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.proto.protobuf.PersonTest buildPartial() {
      com.mumu.proto.protobuf.PersonTest result = new com.mumu.proto.protobuf.PersonTest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.email_ = email_;
      result.sex_ = sex_;
      if (phoneBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.phone_ = phone_;
      } else {
        result.phone_ = phoneBuilder_.build();
      }
      result.tags_ = internalGetTags();
      result.tags_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.proto.protobuf.PersonTest) {
        return mergeFrom((com.mumu.proto.protobuf.PersonTest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.proto.protobuf.PersonTest other) {
      if (other == com.mumu.proto.protobuf.PersonTest.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (other.sex_ != 0) {
        setSexValue(other.getSexValue());
      }
      if (phoneBuilder_ == null) {
        if (!other.phone_.isEmpty()) {
          if (phone_.isEmpty()) {
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePhoneIsMutable();
            phone_.addAll(other.phone_);
          }
          onChanged();
        }
      } else {
        if (!other.phone_.isEmpty()) {
          if (phoneBuilder_.isEmpty()) {
            phoneBuilder_.dispose();
            phoneBuilder_ = null;
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000010);
            phoneBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneFieldBuilder() : null;
          } else {
            phoneBuilder_.addAllMessages(other.phone_);
          }
        }
      }
      internalGetMutableTags().mergeFrom(
          other.internalGetTags());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.proto.protobuf.PersonTest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.proto.protobuf.PersonTest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private int sex_ = 0;
    /**
     * <pre>
     * 枚举类型
     * </pre>
     *
     * <code>.PersonTest.Sex sex = 4;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <pre>
     * 枚举类型
     * </pre>
     *
     * <code>.PersonTest.Sex sex = 4;</code>
     */
    public Builder setSexValue(int value) {
      sex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 枚举类型
     * </pre>
     *
     * <code>.PersonTest.Sex sex = 4;</code>
     */
    public com.mumu.proto.protobuf.PersonTest.Sex getSex() {
      @SuppressWarnings("deprecation")
      com.mumu.proto.protobuf.PersonTest.Sex result = com.mumu.proto.protobuf.PersonTest.Sex.valueOf(sex_);
      return result == null ? com.mumu.proto.protobuf.PersonTest.Sex.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 枚举类型
     * </pre>
     *
     * <code>.PersonTest.Sex sex = 4;</code>
     */
    public Builder setSex(com.mumu.proto.protobuf.PersonTest.Sex value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      sex_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 枚举类型
     * </pre>
     *
     * <code>.PersonTest.Sex sex = 4;</code>
     */
    public Builder clearSex() {
      
      sex_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.mumu.proto.protobuf.PersonTest.PhoneNumber> phone_ =
      java.util.Collections.emptyList();
    private void ensurePhoneIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        phone_ = new java.util.ArrayList<com.mumu.proto.protobuf.PersonTest.PhoneNumber>(phone_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mumu.proto.protobuf.PersonTest.PhoneNumber, com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder, com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder> phoneBuilder_;

    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public java.util.List<com.mumu.proto.protobuf.PersonTest.PhoneNumber> getPhoneList() {
      if (phoneBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phone_);
      } else {
        return phoneBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public int getPhoneCount() {
      if (phoneBuilder_ == null) {
        return phone_.size();
      } else {
        return phoneBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public com.mumu.proto.protobuf.PersonTest.PhoneNumber getPhone(int index) {
      if (phoneBuilder_ == null) {
        return phone_.get(index);
      } else {
        return phoneBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder setPhone(
        int index, com.mumu.proto.protobuf.PersonTest.PhoneNumber value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.set(index, value);
        onChanged();
      } else {
        phoneBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder setPhone(
        int index, com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder addPhone(com.mumu.proto.protobuf.PersonTest.PhoneNumber value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(value);
        onChanged();
      } else {
        phoneBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder addPhone(
        int index, com.mumu.proto.protobuf.PersonTest.PhoneNumber value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(index, value);
        onChanged();
      } else {
        phoneBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder addPhone(
        com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.add(builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder addPhone(
        int index, com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder addAllPhone(
        java.lang.Iterable<? extends com.mumu.proto.protobuf.PersonTest.PhoneNumber> values) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phone_);
        onChanged();
      } else {
        phoneBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder clearPhone() {
      if (phoneBuilder_ == null) {
        phone_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        phoneBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public Builder removePhone(int index) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.remove(index);
        onChanged();
      } else {
        phoneBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder getPhoneBuilder(
        int index) {
      return getPhoneFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      if (phoneBuilder_ == null) {
        return phone_.get(index);  } else {
        return phoneBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public java.util.List<? extends com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder>
         getPhoneOrBuilderList() {
      if (phoneBuilder_ != null) {
        return phoneBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phone_);
      }
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder addPhoneBuilder() {
      return getPhoneFieldBuilder().addBuilder(
          com.mumu.proto.protobuf.PersonTest.PhoneNumber.getDefaultInstance());
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder addPhoneBuilder(
        int index) {
      return getPhoneFieldBuilder().addBuilder(
          index, com.mumu.proto.protobuf.PersonTest.PhoneNumber.getDefaultInstance());
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .PersonTest.PhoneNumber phone = 5;</code>
     */
    public java.util.List<com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder>
         getPhoneBuilderList() {
      return getPhoneFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mumu.proto.protobuf.PersonTest.PhoneNumber, com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder, com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder>
        getPhoneFieldBuilder() {
      if (phoneBuilder_ == null) {
        phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mumu.proto.protobuf.PersonTest.PhoneNumber, com.mumu.proto.protobuf.PersonTest.PhoneNumber.Builder, com.mumu.proto.protobuf.PersonTest.PhoneNumberOrBuilder>(
                phone_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        phone_ = null;
      }
      return phoneBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableTags() {
      onChanged();;
      if (tags_ == null) {
        tags_ = com.google.protobuf.MapField.newMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      if (!tags_.isMutable()) {
        tags_ = tags_.copy();
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTags() {
      internalGetMutableTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    public Builder removeTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableTags() {
      return internalGetMutableTags().getMutableMap();
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    public Builder putTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTags().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    public Builder putAllTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTags().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PersonTest)
  }

  // @@protoc_insertion_point(class_scope:PersonTest)
  private static final com.mumu.proto.protobuf.PersonTest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.proto.protobuf.PersonTest();
  }

  public static com.mumu.proto.protobuf.PersonTest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonTest>
      PARSER = new com.google.protobuf.AbstractParser<PersonTest>() {
    @java.lang.Override
    public PersonTest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersonTest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersonTest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonTest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.proto.protobuf.PersonTest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

