// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JetProtos.proto

package com.mumu.proto.protobuf;

public final class PersonTestProtos {
  private PersonTestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonTest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonTest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonTest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonTest_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonTest_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017JetProtos.proto\"\364\002\n\nPersonTest\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\034\n\003sex" +
      "\030\004 \001(\0162\017.PersonTest.Sex\022&\n\005phone\030\005 \003(\0132\027" +
      ".PersonTest.PhoneNumber\022#\n\004tags\030\006 \003(\0132\025." +
      "PersonTest.TagsEntry\032+\n\tTagsEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032{\n\013PhoneNumber" +
      "\022\016\n\006number\030\001 \001(\t\022/\n\004type\030\002 \001(\0162!.PersonT" +
      "est.PhoneNumber.PhoneType\"+\n\tPhoneType\022\n" +
      "\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"(\n\003Sex\022\013\n" +
      "\007DEFAULT\020\000\022\010\n\004MALE\020\001\022\n\n\006Female\020\002B3\n\035com." +
      "gobestsoft.proto.protobufB\020PersonTestPro" +
      "tosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PersonTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PersonTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonTest_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Sex", "Phone", "Tags", });
    internal_static_PersonTest_TagsEntry_descriptor =
      internal_static_PersonTest_descriptor.getNestedTypes().get(0);
    internal_static_PersonTest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonTest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PersonTest_PhoneNumber_descriptor =
      internal_static_PersonTest_descriptor.getNestedTypes().get(1);
    internal_static_PersonTest_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonTest_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
